"""VEYRA checklist registry.

A registry of security-operations checklists the team can browse and run.
Each checklist declares: purpose, owner, cadence, scope, evidence, remediation,
tier, and a status-chip rule.

This module is metadata-only: it does not execute anything. Checklist execution
belongs to `checklist_runner.py`, which reads from this registry.

Design notes
------------
- Domain is the top-level bucket (live_monitoring, identity, endpoint, ...).
- Category is a finer label inside the domain (Wireless, Auth, ...).
- Tier: essential / recommended / optional — determines default view weight.
- Cadence: realtime / hourly / daily / weekly / monthly / on_demand.
- Owner role: which team member is accountable for running this checklist.
- Status chip rule: deterministic description of when the chip goes green /
  amber / yellow / semi_red / red.
- Boundary: what the checklist must NEVER do (e.g. no deauth, no injection).

Adding a checklist? 1) add the tuple here, 2) run `python scripts/generate_tool_docs.py`
(if applicable), 3) verify with `python scripts/validate_checklist_documentation.py`
or the extended validator.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Domains
# ---------------------------------------------------------------------------

DOMAINS: list[str] = [
    "live_monitoring",
    "identity",
    "endpoint",
    "network_defense",
    "cloud_container",
    "ai_agent",
    "dfir",
    "governance",
    "supply_chain",
    "red_team",
    "blue_team",
]

# ---------------------------------------------------------------------------
# Owner roles (must match UserAccount.role values)
# ---------------------------------------------------------------------------

OWNER_ROLES: list[str] = [
    "sudo",
    "security_admin",
    "security_operator",
    "analyst",
    "viewer",
]

# ---------------------------------------------------------------------------
# Cadences
# ---------------------------------------------------------------------------

CADENCES: list[str] = [
    "realtime",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "on_demand",
]

# ---------------------------------------------------------------------------
# Tiers
# ---------------------------------------------------------------------------

TIERS: list[str] = ["essential", "recommended", "optional"]

# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------
# Each entry is a dict. All keys are required. Keep messages operational.
#
# Field keys:
#   id                unique slug (lowercase, hyphens)
#   domain            one of DOMAINS
#   category          short label
#   name              human name
#   purpose           one-line objective
#   owner_role        one of OWNER_ROLES
#   cadence           one of CADENCES
#   scope             what the checklist inspects (free-form but short)
#   tier              one of TIERS
#   evidence          list of evidence items to capture
#   remediation       what to do on failure
#   status_chip_rule  when the chip goes green/amber/yellow/semi_red/red
#   boundary          what this must NEVER do
#
# ---------------------------------------------------------------------------

CHECKLISTS: list[dict] = [
    # ============================== live_monitoring ==========================
    {
        "id": "wifi-ap-baseline-drift",
        "domain": "live_monitoring",
        "category": "Wireless",
        "name": "Wi-Fi AP baseline drift",
        "purpose": "Detect new/changed/removed access points vs the approved baseline.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "wifi_radio",
        "tier": "essential",
        "evidence": ["bssid", "ssid", "channel", "security", "signal_dbm", "first_seen"],
        "remediation": "Investigate unknown BSSIDs, verify authorized deployments, mark trusted/untrusted.",
        "status_chip_rule": "green=no drift; amber=new AP; yellow=security downgrade; red=rogue or BSSID clone",
        "boundary": "read-only radio scan; no deauth, no injection, no credential capture",
    },
    {
        "id": "wifi-tamper-detection",
        "domain": "live_monitoring",
        "category": "Wireless",
        "name": "Wi-Fi tamper detection",
        "purpose": "Detect SSID/BSSID/channel/security drift on known access points.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "wifi_radio",
        "tier": "essential",
        "evidence": ["bssid", "changed_field", "old_value", "new_value", "observed_at"],
        "remediation": "Correlate with change tickets; if unauthorized, isolate the affected AP segment.",
        "status_chip_rule": "green=no change; amber=cosmetic; yellow=security field changed; red=BSSID clone",
        "boundary": "observe only; do not modify AP state",
    },
    {
        "id": "ethernet-link-monitor",
        "domain": "live_monitoring",
        "category": "Wired",
        "name": "Ethernet link monitoring",
        "purpose": "Monitor link up/down, speed, duplex, PoE events per port.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "switch_ports",
        "tier": "recommended",
        "evidence": ["port_id", "event", "speed_mbps", "duplex", "poe_state", "timestamp"],
        "remediation": "Correlate flaps with change windows and cabling issues; investigate repeated flaps.",
        "status_chip_rule": "green=stable; amber=single flap; yellow=repeated flaps; red=link down on critical port",
        "boundary": "read-only SNMP or sensor data; no port shut/no-shut",
    },
    {
        "id": "device-join-leave-monitor",
        "domain": "live_monitoring",
        "category": "Devices",
        "name": "New connected device watch",
        "purpose": "Detect every new MAC joining the monitored network and why.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "lan_wifi",
        "tier": "essential",
        "evidence": ["mac", "vendor", "ip", "dhcp_hostname", "first_seen", "wifi_or_wired"],
        "remediation": "Verify against DHCP/router inventory; mark trusted or open an investigation.",
        "status_chip_rule": "green=known devices only; amber=1 new; yellow=multiple new; red=new device with untrusted vendor",
        "boundary": "passive collection only; no probes",
    },
    {
        "id": "connection-drop-diagnosis",
        "domain": "live_monitoring",
        "category": "Reliability",
        "name": "Connection drop diagnosis",
        "purpose": "Explain why a wired or wireless connection dropped.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "lan_wifi",
        "tier": "essential",
        "evidence": ["link_id", "drop_time", "dhcp_state", "dns_state", "ap_assoc_state", "signal_dbm"],
        "remediation": "Check cabling, DHCP lease, DNS resolution, AP RSSI; escalate to network owner if repeated.",
        "status_chip_rule": "green=no drop; amber=single drop; yellow=repeated; red=crash-loop or critical-path drop",
        "boundary": "diagnose only; no forced reconnect, no deauth",
    },
    {
        "id": "rogue-ap-correlation",
        "domain": "live_monitoring",
        "category": "Wireless",
        "name": "Rogue AP correlation",
        "purpose": "Correlate suspicious APs with LAN observations and DHCP/DNS.",
        "owner_role": "analyst",
        "cadence": "realtime",
        "scope": "wifi_radio+lan",
        "tier": "essential",
        "evidence": ["bssid", "ssid", "lan_asset_ids", "dhcp_events", "dns_events"],
        "remediation": "Locate AP physically; involve facilities/network owners; contain at switch if authorized.",
        "status_chip_rule": "green=none; amber=unidentified; yellow=identified unmanaged; red=bridging to prod LAN",
        "boundary": "no deauth, no jamming, no forced disassociation",
    },
    {
        "id": "wired-traffic-anomaly",
        "domain": "live_monitoring",
        "category": "Wired",
        "name": "Wired traffic anomaly",
        "purpose": "Detect unusual volume/destination on wired segments vs baseline.",
        "owner_role": "analyst",
        "cadence": "hourly",
        "scope": "switch_ports",
        "tier": "recommended",
        "evidence": ["src", "dst", "port", "bytes_out", "protocol", "baseline_delta"],
        "remediation": "Investigate flow origin; correlate with process/identity; classify as exfil/lateral or benign.",
        "status_chip_rule": "green=within band; amber=1.5x; yellow=3x; red=5x or known exfil destination",
        "boundary": "metadata only; no packet content collection without legal basis",
    },
    {
        "id": "baseline-snapshot-freshness",
        "domain": "live_monitoring",
        "category": "Baseline",
        "name": "Baseline snapshot freshness",
        "purpose": "Ensure each monitored baseline was refreshed within its SLA.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "baselines",
        "tier": "recommended",
        "evidence": ["baseline_id", "owner", "last_refreshed_at", "age_hours"],
        "remediation": "Refresh stale baselines; investigate why the sensor stopped reporting.",
        "status_chip_rule": "green=within SLA; amber=+20%; yellow=+50%; red=stale > SLA",
        "boundary": "compare timestamps only",
    },

    # ============================== identity =================================
    {
        "id": "mfa-coverage",
        "domain": "identity",
        "category": "Auth",
        "name": "MFA coverage",
        "purpose": "Every active human account has MFA enrolled.",
        "owner_role": "security_admin",
        "cadence": "daily",
        "scope": "user_accounts",
        "tier": "essential",
        "evidence": ["user_id", "role", "mfa_enabled", "last_login"],
        "remediation": "Force enrollment; disable login for non-MFA accounts until resolved.",
        "status_chip_rule": "green=100%; amber=≥95%; yellow=≥80%; red=<80% or any privileged account without MFA",
        "boundary": "read-only user metadata; no password operations",
    },
    {
        "id": "privileged-account-review",
        "domain": "identity",
        "category": "Privilege",
        "name": "Privileged account review",
        "purpose": "Confirm each privileged account is still required and owned.",
        "owner_role": "security_admin",
        "cadence": "weekly",
        "scope": "user_accounts",
        "tier": "essential",
        "evidence": ["user_id", "role", "owner", "last_login", "grant_reason"],
        "remediation": "Revoke unused privileges; document owners; require re-attestation.",
        "status_chip_rule": "green=100% attested; amber=≥95%; yellow=≥80%; red=any unattested sudo",
        "boundary": "read-only; changes go through change control",
    },
    {
        "id": "brute-force-detection",
        "domain": "identity",
        "category": "Auth",
        "name": "Brute-force detection",
        "purpose": "Detect repeated failed logins per user/source/host.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "login_events",
        "tier": "essential",
        "evidence": ["username", "src_ip", "host", "attempt_count", "window_seconds"],
        "remediation": "Lock account or throttle source; investigate upstream credentials.",
        "status_chip_rule": "green=0; amber=3; yellow=5; red=10+ within window",
        "boundary": "observe only; lockout requires approval",
    },
    {
        "id": "session-anomaly",
        "domain": "identity",
        "category": "Session",
        "name": "Session anomaly",
        "purpose": "Detect unusual host/application/auth combinations per user.",
        "owner_role": "analyst",
        "cadence": "hourly",
        "scope": "session_events",
        "tier": "recommended",
        "evidence": ["username", "host", "application", "auth_method", "anomaly_score"],
        "remediation": "Contact user; correlate with endpoint telemetry; consider session revocation.",
        "status_chip_rule": "green=<0.5; amber=0.5–0.7; yellow=0.7–0.85; red=≥0.85",
        "boundary": "advisory only",
    },
    {
        "id": "service-account-review",
        "domain": "identity",
        "category": "Privilege",
        "name": "Service account review",
        "purpose": "Detect over-scoped or unused service accounts.",
        "owner_role": "security_admin",
        "cadence": "weekly",
        "scope": "identity",
        "tier": "recommended",
        "evidence": ["account_id", "owner", "scope", "last_used_at", "permissions"],
        "remediation": "Scope-reduce; rotate credentials; require owner attestation.",
        "status_chip_rule": "green=100% reviewed; amber=1 stale; yellow=multiple stale; red=over-privileged + unused",
        "boundary": "read-only review; changes via change control",
    },
    {
        "id": "token-expiry",
        "domain": "identity",
        "category": "Credentials",
        "name": "Long-lived token audit",
        "purpose": "Ensure no API/service tokens outlive policy.",
        "owner_role": "security_admin",
        "cadence": "weekly",
        "scope": "tokens",
        "tier": "recommended",
        "evidence": ["token_id", "owner", "created_at", "expires_at", "scope"],
        "remediation": "Rotate over-age tokens; shorten default TTL; require expiry.",
        "status_chip_rule": "green=within policy; amber=1 overdue; yellow=multiple overdue; red=privileged token >2× policy",
        "boundary": "read-only metadata",
    },

    # ============================== endpoint =================================
    {
        "id": "endpoint-patch-level",
        "domain": "endpoint",
        "category": "Patch",
        "name": "Endpoint patch level",
        "purpose": "Track missing patches against policy per endpoint.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "endpoints",
        "tier": "essential",
        "evidence": ["endpoint_id", "missing_critical", "missing_high", "days_since_patch"],
        "remediation": "Schedule patching; prioritize critical CVEs and internet-facing hosts.",
        "status_chip_rule": "green=0 critical; amber=1; yellow=2–5; red=>5 or any KEV",
        "boundary": "inventory only; no remote execution",
    },
    {
        "id": "endpoint-services-baseline",
        "domain": "endpoint",
        "category": "Services",
        "name": "Listening services baseline",
        "purpose": "Detect unexpected listening ports/processes.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "endpoints",
        "tier": "essential",
        "evidence": ["endpoint_id", "port", "protocol", "process", "user", "expected"],
        "remediation": "Investigate drift; kill unauthorized services (with approval); update baseline.",
        "status_chip_rule": "green=0 drift; amber=1; yellow=2–4; red=any on critical host or privileged user",
        "boundary": "observe only; changes via change control",
    },
    {
        "id": "endpoint-usb-dlp",
        "domain": "endpoint",
        "category": "USB/DLP",
        "name": "USB & DLP event review",
        "purpose": "Review USB mass storage and secret-detection events.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "endpoints",
        "tier": "essential",
        "evidence": ["endpoint_id", "device_id", "event", "detected_secret_count", "policy_decision"],
        "remediation": "Contact owner; if secrets detected, rotate immediately; block device class if unauthorized.",
        "status_chip_rule": "green=0; amber=1 benign; yellow=1 with secrets; red=multiple or privileged host",
        "boundary": "observe only; USB blocking is a separate control",
    },
    {
        "id": "endpoint-edr-health",
        "domain": "endpoint",
        "category": "EDR",
        "name": "EDR/AV health",
        "purpose": "Confirm each endpoint reports healthy EDR/AV.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "endpoints",
        "tier": "essential",
        "evidence": ["endpoint_id", "edr_state", "last_heartbeat_at", "signature_age_days"],
        "remediation": "Re-enable or reinstall EDR; isolate endpoint if it stays dark beyond SLA.",
        "status_chip_rule": "green=100%; amber=≥95%; yellow=≥80%; red=any critical host offline",
        "boundary": "read-only state; no remote uninstall",
    },
    {
        "id": "endpoint-autorun-review",
        "domain": "endpoint",
        "category": "Persistence",
        "name": "Autorun / startup review",
        "purpose": "Detect new or unexpected autorun entries.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "endpoints",
        "tier": "recommended",
        "evidence": ["endpoint_id", "entry_name", "path", "user", "first_seen"],
        "remediation": "Investigate each new entry; remove unauthorized persistence with approval.",
        "status_chip_rule": "green=0 new; amber=1 known; yellow=multiple or unknown; red=unsigned binary in temp",
        "boundary": "observe only; removal via change control",
    },

    # ============================== network_defense ==========================
    {
        "id": "ids-health",
        "domain": "network_defense",
        "category": "IDS",
        "name": "IDS/NSM health (Suricata)",
        "purpose": "Confirm IDS sensor captures traffic and reports heartbeats.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "sensor",
        "tier": "essential",
        "evidence": ["sensor_id", "last_heartbeat_at", "interface_state", "pps", "alerts_24h"],
        "remediation": "Restore interface; if capture down on critical segment, escalate immediately.",
        "status_chip_rule": "green=healthy; amber=1 miss; yellow=2+; red=dark on critical segment",
        "boundary": "read-only; no packet modification",
    },
    {
        "id": "dns-anomaly-review",
        "domain": "network_defense",
        "category": "DNS",
        "name": "DNS anomaly review",
        "purpose": "Detect DGA, tunneling, NXDOMAIN spikes.",
        "owner_role": "analyst",
        "cadence": "hourly",
        "scope": "dns_queries",
        "tier": "recommended",
        "evidence": ["query", "client_ip", "answer", "nxdomain_rate", "entropy_score"],
        "remediation": "Block/review domain; correlate with endpoint telemetry; add detection.",
        "status_chip_rule": "green=baseline; amber=2×; yellow=5×; red=tunnel signature or known C2",
        "boundary": "metadata only",
    },
    {
        "id": "tls-cert-expiry",
        "domain": "network_defense",
        "category": "TLS",
        "name": "TLS certificate expiry",
        "purpose": "Track certs within N days of expiry.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "inventory",
        "tier": "essential",
        "evidence": ["cert_id", "subject", "expires_at", "days_remaining", "serial"],
        "remediation": "Renew before expiry; if self-signed on prod, escalate.",
        "status_chip_rule": "green=>30d; amber=15–30d; yellow=7–15d; red=<7d or expired",
        "boundary": "read-only scan",
    },
    {
        "id": "network-segmentation-check",
        "domain": "network_defense",
        "category": "Segmentation",
        "name": "Network segmentation check",
        "purpose": "Detect unexpected cross-zone flows.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "flows",
        "tier": "recommended",
        "evidence": ["src_zone", "dst_zone", "protocol", "port", "flow_count"],
        "remediation": "Tighten firewall rules; confirm with network owner.",
        "status_chip_rule": "green=0 unexpected; amber=1; yellow=2+; red=critical asset crossed",
        "boundary": "analysis only; no firewall changes",
    },
    {
        "id": "flow-baseline-drift",
        "domain": "network_defense",
        "category": "Flows",
        "name": "Flow baseline drift",
        "purpose": "Detect new src/dst/port combinations vs baseline.",
        "owner_role": "analyst",
        "cadence": "hourly",
        "scope": "flows",
        "tier": "recommended",
        "evidence": ["src", "dst", "port", "protocol", "first_seen"],
        "remediation": "Correlate with change windows; classify as authorized or investigate.",
        "status_chip_rule": "green=0; amber=1 low-risk; yellow=multiple; red=new flow to sensitive asset",
        "boundary": "metadata only",
    },

    # ============================== cloud_container ==========================
    {
        "id": "cloud-public-exposure",
        "domain": "cloud_container",
        "category": "Cloud",
        "name": "Cloud public exposure review",
        "purpose": "Detect public buckets, open security groups, exposed LBs.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "cloud_resources",
        "tier": "essential",
        "evidence": ["resource_id", "provider", "region", "exposure_type", "public"],
        "remediation": "Remove public access; add policy guardrails.",
        "status_chip_rule": "green=0; amber=1 non-sensitive; yellow=1 sensitive; red=any prod data store",
        "boundary": "read-only inventory via approved connector",
    },
    {
        "id": "cloud-iam-privilege-drift",
        "domain": "cloud_container",
        "category": "Cloud IAM",
        "name": "Cloud IAM privilege drift",
        "purpose": "Detect new admin/owner bindings or over-scoped roles.",
        "owner_role": "security_admin",
        "cadence": "daily",
        "scope": "cloud_iam",
        "tier": "essential",
        "evidence": ["principal", "role", "resource", "granted_at", "granted_by"],
        "remediation": "Revoke unauthorized; scope-reduce; require change ticket.",
        "status_chip_rule": "green=0; amber=1 low-impact; yellow=admin non-prod; red=admin on prod or external principal",
        "boundary": "read-only; changes via change control",
    },
    {
        "id": "container-image-digest",
        "domain": "cloud_container",
        "category": "Containers",
        "name": "Container image digest pinning",
        "purpose": "Ensure running containers use immutable digests.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "containers",
        "tier": "recommended",
        "evidence": ["workload", "namespace", "image", "digest_pinned"],
        "remediation": "Replace floating tags with digests; enforce admission policy.",
        "status_chip_rule": "green=100%; amber=≥95%; yellow=≥80%; red=any prod critical workload",
        "boundary": "read-only",
    },
    {
        "id": "k8s-rbac-baseline",
        "domain": "cloud_container",
        "category": "Kubernetes",
        "name": "Kubernetes RBAC baseline",
        "purpose": "Detect overly broad cluster-role bindings.",
        "owner_role": "security_operator",
        "cadence": "weekly",
        "scope": "k8s",
        "tier": "recommended",
        "evidence": ["subject", "role", "namespace", "cluster_scope", "first_seen"],
        "remediation": "Scope-reduce; use namespaced roles; require approval.",
        "status_chip_rule": "green=0; amber=1 dev; yellow=multiple; red=cluster-admin on user",
        "boundary": "read-only via kubeconfig with least-privilege",
    },
    {
        "id": "secret-scan-repo",
        "domain": "cloud_container",
        "category": "Secrets",
        "name": "Secret scan in repos",
        "purpose": "Detect accidentally committed secrets.",
        "owner_role": "security_operator",
        "cadence": "realtime",
        "scope": "repos",
        "tier": "essential",
        "evidence": ["repo", "path", "secret_type", "commit", "detected_at"],
        "remediation": "Rotate leaked secret; rewrite history; add pre-commit hook.",
        "status_chip_rule": "green=0; amber=1 low-value; yellow=1 high-value; red=any prod secret",
        "boundary": "read-only git scan",
    },

    # ============================== ai_agent =================================
    {
        "id": "prompt-injection-battery",
        "domain": "ai_agent",
        "category": "AI Red",
        "name": "Prompt injection battery",
        "purpose": "Run the governed prompt-injection battery against an approved target.",
        "owner_role": "analyst",
        "cadence": "weekly",
        "scope": "approved_ai_asset",
        "tier": "essential",
        "evidence": ["asset_id", "probe_id", "policy_decision", "refusal_state", "trace_id"],
        "remediation": "Harden guardrails; add policy; re-run until stable.",
        "status_chip_rule": "green=100% refused; amber=1 bypass; yellow=multiple; red=any confidential-data leak",
        "boundary": "lab/approved only; no exploit delivery",
    },
    {
        "id": "rag-retrieval-audit",
        "domain": "ai_agent",
        "category": "RAG",
        "name": "RAG retrieval audit",
        "purpose": "Confirm retrieval filters enforce tenant/authz policy.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "vector_db",
        "tier": "essential",
        "evidence": ["query_id", "tenant", "returned_docs", "policy_decision"],
        "remediation": "Fix authz filter; re-index if contamination suspected.",
        "status_chip_rule": "green=100% filtered; amber=1 warning; yellow=cross-tenant; red=any sensitive doc leak",
        "boundary": "read-only query tracing",
    },
    {
        "id": "mcp-server-inventory",
        "domain": "ai_agent",
        "category": "MCP",
        "name": "MCP server inventory",
        "purpose": "Ensure every MCP server is authorized and inventoried.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "mcp",
        "tier": "recommended",
        "evidence": ["server_id", "owner", "scope", "first_seen", "version"],
        "remediation": "Decommission unapproved servers; register with owner and version.",
        "status_chip_rule": "green=0 unknown; amber=1 dev; yellow=multiple; red=prod data access",
        "boundary": "inventory only",
    },
    {
        "id": "tool-allowlist-drift",
        "domain": "ai_agent",
        "category": "Agents",
        "name": "Agent tool allowlist drift",
        "purpose": "Detect agents calling tools outside their allowlist.",
        "owner_role": "analyst",
        "cadence": "realtime",
        "scope": "agent_runtime",
        "tier": "essential",
        "evidence": ["agent_id", "tool_name", "policy_decision", "trace_id", "denied"],
        "remediation": "Block or re-scope; add policy; notify agent owner.",
        "status_chip_rule": "green=0 denied; amber=1 low-impact; yellow=multiple; red=high-impact tool attempted",
        "boundary": "observe only; enforcement via gateway",
    },
    {
        "id": "agent-identity-mfa",
        "domain": "ai_agent",
        "category": "Agents",
        "name": "Agent identity coverage",
        "purpose": "Every agent has cryptographic identity + owner + revocation path.",
        "owner_role": "security_admin",
        "cadence": "weekly",
        "scope": "agent_identities",
        "tier": "essential",
        "evidence": ["agent_id", "identity_scheme", "owner", "revoked_at"],
        "remediation": "Enroll unmanaged; register owner; establish revocation.",
        "status_chip_rule": "green=100%; amber=≥95%; yellow=≥80%; red=any unmanaged prod agent",
        "boundary": "registry only",
    },
    {
        "id": "trajectory-assurance",
        "domain": "ai_agent",
        "category": "Agents",
        "name": "Trajectory assurance",
        "purpose": "Confirm full agent trajectory + evidence chain per decision.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "agent_runtime",
        "tier": "recommended",
        "evidence": ["trace_id", "evidence_sha256", "actions_count", "verification_state"],
        "remediation": "Enable hash-chained evidence; investigate gaps.",
        "status_chip_rule": "green=100% hash-chained; amber=≥95%; yellow=≥80%; red=any missing evidence on privileged action",
        "boundary": "read-only trace",
    },

    # ============================== dfir =====================================
    {
        "id": "evidence-custody-check",
        "domain": "dfir",
        "category": "Evidence",
        "name": "Evidence chain of custody",
        "purpose": "Confirm every evidence artifact has hash + custodian + transfer log.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "evidence",
        "tier": "essential",
        "evidence": ["artifact_id", "sha256", "custodian", "created_at", "last_transfer_at"],
        "remediation": "Restore custody record; re-hash if integrity uncertain.",
        "status_chip_rule": "green=100%; amber=≥95%; yellow=≥80%; red=any prod evidence without hash",
        "boundary": "read-only metadata",
    },
    {
        "id": "case-sla-tracker",
        "domain": "dfir",
        "category": "Cases",
        "name": "Case SLA tracker",
        "purpose": "Ensure investigations close within SLA.",
        "owner_role": "security_operator",
        "cadence": "daily",
        "scope": "cases",
        "tier": "recommended",
        "evidence": ["case_id", "opened_at", "target_close_at", "state"],
        "remediation": "Escalate overdue; investigate why SLAs are missed.",
        "status_chip_rule": "green=on time; amber=1 overdue; yellow=multiple; red=critical overdue",
        "boundary": "metadata only",
    },
    {
        "id": "yara-rule-health",
        "domain": "dfir",
        "category": "Detection",
        "name": "YARA rule health",
        "purpose": "Ensure YARA rules compile and are current.",
        "owner_role": "analyst",
        "cadence": "weekly",
        "scope": "rules",
        "tier": "recommended",
        "evidence": ["rule_id", "compiled", "last_run_at", "false_positive_rate"],
        "remediation": "Fix compile errors; retire noisy rules; tune thresholds.",
        "status_chip_rule": "green=100% compile; amber=1 error; yellow=multiple; red=critical rule disabled",
        "boundary": "read-only check",
    },
    {
        "id": "timeline-completeness",
        "domain": "dfir",
        "category": "Timeline",
        "name": "Timeline completeness",
        "purpose": "Verify timelines cover required sources.",
        "owner_role": "analyst",
        "cadence": "daily",
        "scope": "cases",
        "tier": "recommended",
        "evidence": ["case_id", "sources_expected", "sources_present", "gaps"],
        "remediation": "Collect missing sources; document gaps.",
        "status_chip_rule": "green=100%; amber=1 gap; yellow=multiple; red=critical source missing",
        "boundary": "read-only",
    },
    {
        "id": "hash-verification",
        "domain": "dfir",
        "category": "Integrity",
        "name": "Evidence hash verification",
        "purpose": "Re-verify stored evidence hashes match original.",
        "owner_role": "analyst",
        "cadence": "weekly",
                "scope": "evidence",
        "tier": "essential",
        "evidence": ["artifact_id", "sha256", "original_sha256", "verified_at", "verified_by"],
        "remediation": "Re-collect evidence if hash mismatch persists; treat as integrity incident; document in case record.",
        "status_chip_rule": "green=100% match; amber=1 mismatch pending review; yellow=multiple mismatches; red=any mismatch on prod evidence",
        "boundary": "read-only verification; no evidence modification",
    },
]
