"""Extended VEYRA security-tool catalog.
Generated from the current Kali 2026.3.2 tool/metapackage inventory plus a curated
AI/cloud/AppSec/DFIR extension set. This module is catalog metadata only: it never
executes installation or tool commands.
"""
from __future__ import annotations
from .admin_tools import TOOL_REGISTRY, PRIVILEGED_ADMIN_TOOLS
from app.services.slug import slugify

EXTENDED_TOOL_REGISTRY = [

    ('adaptixc2', 'Security Utilities',
     'Kali security utility: adaptixc2', 'isolated_worker'),
    ('airgeddon', 'AI Security', 'Kali security utility: airgeddon', 'isolated_worker'),
    ('altdns', 'Attack Surface', 'Kali security utility: altdns', 'approved_worker'),
    ('android-sdk', 'Security Utilities',
     'Kali security utility: android-sdk', 'approved_worker'),
    ('apple-bleee', 'Security Utilities',
     'Kali security utility: apple-bleee', 'approved_worker'),
    ('arjun', 'Web/API', 'Kali security utility: arjun', 'approved_worker'),
    ('arsenal-ng', 'Security Utilities',
     'Kali security utility: arsenal-ng', 'approved_worker'),
    ('autorecon', 'Attack Surface',
     'Kali security utility: autorecon', 'approved_worker'),
    ('azurehound', 'Cloud', 'Kali security utility: azurehound', 'approved_worker'),
    ('b374k', 'Security Utilities', 'Kali security utility: b374k', 'approved_worker'),
    ('berate-ap', 'Security Utilities',
     'Kali security utility: berate-ap', 'approved_worker'),
    ('bettercap-ui', 'Wireless',
     'Kali security utility: bettercap-ui', 'approved_worker'),
    ('bing-ip2hosts', 'Security Utilities',
     'Kali security utility: bing-ip2hosts', 'approved_worker'),
    ('bloodhound', 'Identity', 'Kali security utility: bloodhound', 'isolated_worker'),
    ('bloodhound-ce-python', 'Identity',
     'Kali security utility: bloodhound-ce-python', 'isolated_worker'),
    ('bloodhound.py', 'Identity',
     'Kali security utility: bloodhound.py', 'isolated_worker'),
    ('bloodyad', 'Identity', 'Kali security utility: bloodyad', 'approved_worker'),
    ('bopscrk', 'Security Utilities',
     'Kali security utility: bopscrk', 'approved_worker'),
    ('bpf-linker', 'Security Utilities',
     'Kali security utility: bpf-linker', 'approved_worker'),
    ('bruteforce-luks', 'Security Utilities',
     'Kali security utility: bruteforce-luks', 'isolated_worker'),
    ('bruteforce-salted-openssl', 'Security Utilities',
     'Kali security utility: bruteforce-salted-openssl', 'isolated_worker'),
    ('bruteforce-wallet', 'Security Utilities',
     'Kali security utility: bruteforce-wallet', 'isolated_worker'),
    ('bruteshark', 'Security Utilities',
     'Kali security utility: bruteshark', 'isolated_worker'),
    ('brutespray', 'Credential Audit',
     'Kali security utility: brutespray', 'isolated_worker'),
    ('caido', 'AI Security', 'Kali security utility: caido', 'approved_worker'),
    ('caido-cli', 'AI Security', 'Kali security utility: caido-cli', 'approved_worker'),
    ('calicoctl', 'Security Utilities',
     'Kali security utility: calicoctl', 'approved_worker'),
    ('capstone-tool', 'Reverse Engineering',
     'Kali security utility: capstone-tool', 'approved_worker'),
    ('certgraph', 'Security Utilities',
     'Kali security utility: certgraph', 'approved_worker'),
    ('certi', 'Security Utilities', 'Kali security utility: certi', 'approved_worker'),
    ('chainsaw', 'AI Security', 'Kali security utility: chainsaw', 'approved_worker'),
    ('changeme', 'Security Utilities',
     'Kali security utility: changeme', 'approved_worker'),
    ('chaosreader', 'Security Utilities',
     'Kali security utility: chaosreader', 'approved_worker'),
    ('chisel', 'Security Utilities',
     'Kali security utility: chisel', 'isolated_worker'),
    ('chisel-common-binaries', 'Security Utilities',
     'Kali security utility: chisel-common-binaries', 'isolated_worker'),
    ('cilium-cli', 'Kubernetes', 'Kali security utility: cilium-cli', 'approved_worker'),
    ('cisco7crack', 'Credential Audit',
     'Kali security utility: cisco7crack', 'approved_worker'),
    ('cloud-enum', 'Cloud', 'Kali security utility: cloud-enum', 'approved_worker'),
    ('cloudbrute', 'Cloud', 'Kali security utility: cloudbrute', 'isolated_worker'),
    ('cmseek', 'Security Utilities',
     'Kali security utility: cmseek', 'approved_worker'),
    ('cntlm', 'Security Utilities', 'Kali security utility: cntlm', 'approved_worker'),
    ('coercer', 'Identity', 'Kali security utility: coercer', 'isolated_worker'),
    ('colly', 'Security Utilities', 'Kali security utility: colly', 'approved_worker'),
    ('cosign', 'Security Utilities',
     'Kali security utility: cosign', 'approved_worker'),
    ('crack', 'Credential Audit', 'Kali security utility: crack', 'approved_worker'),
    ('crackmapexec', 'Credential Audit',
     'Kali security utility: crackmapexec', 'isolated_worker'),
    ('cri-tools', 'Security Utilities',
     'Kali security utility: cri-tools', 'approved_worker'),
    ('crlfuzz', 'Security Utilities',
     'Kali security utility: crlfuzz', 'approved_worker'),
    ('crowbar', 'Security Utilities',
     'Kali security utility: crowbar', 'isolated_worker'),
    ('cupid-hostapd', 'Wireless',
     'Kali security utility: cupid-hostapd', 'approved_worker'),
    ('cupid-wpasupplicant', 'Security Utilities',
     'Kali security utility: cupid-wpasupplicant', 'approved_worker'),
    ('defectdojo', 'AppSec', 'Kali security utility: defectdojo', 'approved_worker'),
    ('detect-it-easy', 'Reverse Engineering',
     'Kali security utility: detect-it-easy', 'approved_worker'),
    ('dirbuster', 'Security Utilities',
     'Kali security utility: dirbuster', 'approved_worker'),
    ('dislocker', 'Security Utilities',
     'Kali security utility: dislocker', 'approved_worker'),
    ('dnscat2', 'Attack Surface', 'Kali security utility: dnscat2', 'isolated_worker'),
    ('dnsgen', 'Attack Surface', 'Kali security utility: dnsgen', 'approved_worker'),
    ('dnstwist', 'Attack Surface', 'Kali security utility: dnstwist', 'approved_worker'),
    ('donut', 'Security Utilities', 'Kali security utility: donut', 'isolated_worker'),
    ('dscan', 'Security Utilities', 'Kali security utility: dscan', 'approved_worker'),
    ('dufflebag', 'Security Utilities',
     'Kali security utility: dufflebag', 'approved_worker'),
    ('dumpsterdiver', 'Security Utilities',
     'Kali security utility: dumpsterdiver', 'approved_worker'),
    ('dwarf2json', 'Security Utilities',
     'Kali security utility: dwarf2json', 'approved_worker'),
    ('eaphammer', 'Security Utilities',
     'Kali security utility: eaphammer', 'approved_worker'),
    ('eksctl', 'Security Utilities',
     'Kali security utility: eksctl', 'approved_worker'),
    ('email2phonenumber', 'AI Security',
     'Kali security utility: email2phonenumber', 'approved_worker'),
    ('emailharvester', 'AI Security',
     'Kali security utility: emailharvester', 'approved_worker'),
    ('enum4linux-ng', 'Security Utilities',
     'Kali security utility: enum4linux-ng', 'approved_worker'),
    ('evil-ssdp', 'Security Utilities',
     'Kali security utility: evil-ssdp', 'isolated_worker'),
    ('evil-winrm-py', 'Security Utilities',
     'Kali security utility: evil-winrm-py', 'approved_worker'),
    ('evilginx2', 'Security Utilities',
     'Kali security utility: evilginx2', 'isolated_worker'),
    ('exiflooter', 'Security Utilities',
     'Kali security utility: exiflooter', 'approved_worker'),
    ('exploitdb-bin-sploits', 'Exploit Validation',
     'Kali security utility: exploitdb-bin-sploits', 'approved_worker'),
    ('exploitdb-papers', 'Exploit Validation',
     'Kali security utility: exploitdb-papers', 'approved_worker'),
    ('faraday', 'Security Utilities',
     'Kali security utility: faraday', 'approved_worker'),
    ('faraday-agent-dispatcher', 'AI Security',
     'Kali security utility: faraday-agent-dispatcher', 'approved_worker'),
    ('faraday-cli', 'Security Utilities',
     'Kali security utility: faraday-cli', 'approved_worker'),
    ('fatcat', 'Security Utilities',
     'Kali security utility: fatcat', 'approved_worker'),
    ('feroxbuster', 'Web/API', 'Kali security utility: feroxbuster', 'approved_worker'),
    ('finalrecon', 'Attack Surface',
     'Kali security utility: finalrecon', 'approved_worker'),
    ('findomain', 'AI Security', 'Kali security utility: findomain', 'approved_worker'),
    ('fluxion', 'Security Utilities',
     'Kali security utility: fluxion', 'isolated_worker'),
    ('freeradius', 'Security Utilities',
     'Kali security utility: freeradius', 'approved_worker'),
    ('gdb-peda', 'Reverse Engineering',
     'Kali security utility: gdb-peda', 'approved_worker'),
    ('gef', 'Security Utilities', 'Kali security utility: gef', 'approved_worker'),
    ('gemini-cli', 'Security Utilities',
     'Kali security utility: gemini-cli', 'approved_worker'),
    ('getallurls', 'Security Utilities',
     'Kali security utility: getallurls', 'approved_worker'),
    ('getsploit', 'Security Utilities',
     'Kali security utility: getsploit', 'approved_worker'),
    ('gitleaks', 'AppSec', 'Kali security utility: gitleaks', 'approved_worker'),
    ('gitxray', 'Security Utilities',
     'Kali security utility: gitxray', 'approved_worker'),
    ('godoh', 'Security Utilities', 'Kali security utility: godoh', 'approved_worker'),
    ('golang-github-binject-go-donut', 'Security Utilities',
     'Kali security utility: golang-github-binject-go-donut', 'isolated_worker'),
    ('goldeneye', 'Security Utilities',
     'Kali security utility: goldeneye', 'approved_worker'),
    ('goofile', 'Security Utilities',
     'Kali security utility: goofile', 'approved_worker'),
    ('google-nexus-tools', 'Security Utilities',
     'Kali security utility: google-nexus-tools', 'approved_worker'),
    ('goshs', 'Security Utilities', 'Kali security utility: goshs', 'approved_worker'),
    ('gospider', 'Security Utilities',
     'Kali security utility: gospider', 'approved_worker'),
    ('gowitness', 'Security Utilities',
     'Kali security utility: gowitness', 'approved_worker'),
    ('graudit', 'Security Utilities',
     'Kali security utility: graudit', 'approved_worker'),
    ('gsocket', 'Security Utilities',
     'Kali security utility: gsocket', 'isolated_worker'),
    ('gtkhash', 'Credential Audit',
     'Kali security utility: gtkhash', 'approved_worker'),
    ('h8mail', 'AI Security', 'Kali security utility: h8mail', 'approved_worker'),
    ('hak5-wifi-coconut', 'Wireless',
     'Kali security utility: hak5-wifi-coconut', 'approved_worker'),
    ('hashrat', 'Credential Audit',
     'Kali security utility: hashrat', 'approved_worker'),
    ('havoc', 'Security Utilities', 'Kali security utility: havoc', 'isolated_worker'),
    ('hb-honeypot', 'Security Utilities',
     'Kali security utility: hb-honeypot', 'approved_worker'),
    ('hcxtools', 'Wireless', 'Kali security utility: hcxtools', 'approved_worker'),
    ('hekatomb', 'Security Utilities',
     'Kali security utility: hekatomb', 'approved_worker'),
    ('hexstrike-ai', 'AI Security',
     'Kali security utility: hexstrike-ai', 'approved_worker'),
    ('hexwalk', 'Security Utilities',
     'Kali security utility: hexwalk', 'approved_worker'),
    ('hoaxshell', 'Security Utilities',
     'Kali security utility: hoaxshell', 'isolated_worker'),
    ('horst', 'Security Utilities', 'Kali security utility: horst', 'approved_worker'),
    ('hostapd-mana', 'Wireless',
     'Kali security utility: hostapd-mana', 'approved_worker'),
    ('hosthunter', 'Security Utilities',
     'Kali security utility: hosthunter', 'approved_worker'),
    ('hostsman', 'Security Utilities',
     'Kali security utility: hostsman', 'approved_worker'),
    ('htshells', 'Security Utilities',
     'Kali security utility: htshells', 'approved_worker'),
    ('httprobe', 'Security Utilities',
     'Kali security utility: httprobe', 'approved_worker'),
    ('httpx-toolkit', 'Web/API',
     'Kali security utility: httpx-toolkit', 'approved_worker'),
    ('hubble', 'Kubernetes', 'Kali security utility: hubble', 'approved_worker'),
    ('humble', 'Security Utilities',
     'Kali security utility: humble', 'approved_worker'),
    ('hurl', 'Security Utilities', 'Kali security utility: hurl', 'approved_worker'),
    ('ibombshell', 'Security Utilities',
     'Kali security utility: ibombshell', 'approved_worker'),
    ('ident-user-enum', 'Security Utilities',
     'Kali security utility: ident-user-enum', 'approved_worker'),
    ('imhex', 'Reverse Engineering', 'Kali security utility: imhex', 'approved_worker'),
    ('inspy', 'Security Utilities', 'Kali security utility: inspy', 'approved_worker'),
    ('instaloader', 'Security Utilities',
     'Kali security utility: instaloader', 'approved_worker'),
    ('ipv6toolkit', 'Security Utilities',
     'Kali security utility: ipv6toolkit', 'approved_worker'),
    ('ismtp', 'Security Utilities', 'Kali security utility: ismtp', 'approved_worker'),
    ('ivre', 'Network Discovery', 'Kali security utility: ivre', 'approved_worker'),
    ('joplin', 'Security Utilities',
     'Kali security utility: joplin', 'approved_worker'),
    ('jsp-file-browser', 'Security Utilities',
     'Kali security utility: jsp-file-browser', 'approved_worker'),
    ('kali-community-wallpapers', 'Security Utilities',
     'Kali security utility: kali-community-wallpapers', 'approved_worker'),
    ('kerberoast', 'Security Utilities',
     'Kali security utility: kerberoast', 'approved_worker'),
    ('knocker', 'Security Utilities',
     'Kali security utility: knocker', 'approved_worker'),
    ('koadic', 'Security Utilities',
     'Kali security utility: koadic', 'isolated_worker'),
    ('krbrelayx', 'Security Utilities',
     'Kali security utility: krbrelayx', 'approved_worker'),
    ('kubernetes-helm', 'Kubernetes',
     'Kali security utility: kubernetes-helm', 'approved_worker'),
    ('kustomize', 'Security Utilities',
     'Kali security utility: kustomize', 'approved_worker'),
    ('lapsdumper', 'Security Utilities',
     'Kali security utility: lapsdumper', 'approved_worker'),
    ('ldeep', 'Security Utilities', 'Kali security utility: ldeep', 'approved_worker'),
    ('legba', 'Security Utilities', 'Kali security utility: legba', 'approved_worker'),
    ('ligolo-mp', 'Security Utilities',
     'Kali security utility: ligolo-mp', 'isolated_lab_only'),
    ('ligolo-ng', 'Security Utilities',
     'Kali security utility: ligolo-ng', 'isolated_lab_only'),
    ('ligolo-ng-common-binaries', 'Security Utilities',
     'Kali security utility: ligolo-ng-common-binaries', 'isolated_lab_only'),
    ('linkedin2username', 'Security Utilities',
     'Kali security utility: linkedin2username', 'approved_worker'),
    ('linux-exploit-suggester', 'Exploit Validation',
     'Kali security utility: linux-exploit-suggester', 'approved_worker'),
    ('llm-tools-nmap', 'AI Security',
     'Kali security utility: llm-tools-nmap', 'approved_worker'),
    ('maltego-teeth', 'Attack Surface',
     'Kali security utility: maltego-teeth', 'approved_worker'),
    ('maryam', 'Security Utilities',
     'Kali security utility: maryam', 'approved_worker'),
    ('massdns', 'Attack Surface', 'Kali security utility: massdns', 'approved_worker'),
    ('mcp-kali-server', 'Security Utilities',
     'Kali security utility: mcp-kali-server', 'approved_worker'),
    ('merlin-agent', 'AI Security',
     'Kali security utility: merlin-agent', 'isolated_worker'),
    ('merlin-server', 'Security Utilities',
     'Kali security utility: merlin-server', 'isolated_worker'),
    ('metasploitmcp', 'Exploit Validation',
     'Kali security utility: metasploitmcp', 'isolated_worker'),
    ('mitm6', 'Security Utilities', 'Kali security utility: mitm6', 'isolated_worker'),
    ('mongo-tools', 'Security Utilities',
     'Kali security utility: mongo-tools', 'approved_worker'),
    ('mssqlpwner', 'Security Utilities',
     'Kali security utility: mssqlpwner', 'approved_worker'),
    ('multiforcer', 'Security Utilities',
     'Kali security utility: multiforcer', 'approved_worker'),
    ('mxcheck', 'Security Utilities',
     'Kali security utility: mxcheck', 'approved_worker'),
    ('naabu', 'Network Discovery', 'Kali security utility: naabu', 'approved_worker'),
    ('name-that-hash', 'Credential Audit',
     'Kali security utility: name-that-hash', 'approved_worker'),
    ('nbtscan-unixwiz', 'Security Utilities',
     'Kali security utility: nbtscan-unixwiz', 'approved_worker'),
    ('netscanner', 'Network Discovery',
     'Kali security utility: netscanner', 'approved_worker'),
    ('nextnet', 'Security Utilities',
     'Kali security utility: nextnet', 'approved_worker'),
    ('nmapsi4', 'Network Discovery',
     'Kali security utility: nmapsi4', 'approved_worker'),
    ('nuclei', 'Web/API', 'Kali security utility: nuclei', 'approved_worker'),
    ('obsidian', 'Security Utilities',
     'Kali security utility: obsidian', 'approved_worker'),
    ('odat', 'Security Utilities', 'Kali security utility: odat', 'approved_worker'),
    ('oletools', 'Security Utilities',
     'Kali security utility: oletools', 'approved_worker'),
    ('opentaxii', 'Threat Intelligence',
     'Kali security utility: opentaxii', 'approved_worker'),
    ('osrframework', 'Security Utilities',
     'Kali security utility: osrframework', 'approved_worker'),
    ('owl', 'Security Utilities', 'Kali security utility: owl', 'approved_worker'),
    ('pacu', 'Cloud', 'Kali security utility: pacu', 'approved_worker'),
    ('parsero', 'Security Utilities',
     'Kali security utility: parsero', 'approved_worker'),
    ('passdetective', 'Security Utilities',
     'Kali security utility: passdetective', 'approved_worker'),
    ('patchleaks', 'Security Utilities',
     'Kali security utility: patchleaks', 'approved_worker'),
    ('payloadsallthethings', 'Security Utilities',
     'Kali security utility: payloadsallthethings', 'isolated_worker'),
    ('peirates', 'Kubernetes', 'Kali security utility: peirates', 'approved_worker'),
    ('penelope', 'Security Utilities',
     'Kali security utility: penelope', 'approved_worker'),
    ('phishery', 'Security Utilities',
     'Kali security utility: phishery', 'isolated_worker'),
    ('photon', 'Security Utilities',
     'Kali security utility: photon', 'approved_worker'),
    ('phpggc', 'Security Utilities',
     'Kali security utility: phpggc', 'isolated_worker'),
    ('phpsploit', 'Security Utilities',
     'Kali security utility: phpsploit', 'isolated_worker'),
    ('pnscan', 'Security Utilities',
     'Kali security utility: pnscan', 'approved_worker'),
    ('pocsuite3', 'Exploit Validation',
     'Kali security utility: pocsuite3', 'isolated_worker'),
    ('pompem', 'Security Utilities',
     'Kali security utility: pompem', 'approved_worker'),
    ('portspoof', 'Security Utilities',
     'Kali security utility: portspoof', 'isolated_worker'),
    ('poshc2', 'Security Utilities',
     'Kali security utility: poshc2', 'isolated_worker'),
    ('princeprocessor', 'Security Utilities',
     'Kali security utility: princeprocessor', 'approved_worker'),
    ('proxify', 'Security Utilities',
     'Kali security utility: proxify', 'approved_worker'),
    ('proximoth', 'Security Utilities',
     'Kali security utility: proximoth', 'approved_worker'),
    ('proxmark3', 'Wireless', 'Kali security utility: proxmark3', 'approved_worker'),
    ('pskracker', 'Security Utilities',
     'Kali security utility: pskracker', 'approved_worker'),
    ('pspy', 'Security Utilities', 'Kali security utility: pspy', 'approved_worker'),
    ('pwncat', 'Security Utilities',
     'Kali security utility: pwncat', 'isolated_worker'),
    ('pyinstxtractor', 'Security Utilities',
     'Kali security utility: pyinstxtractor', 'approved_worker'),
    ('python3-atomic-operator', 'Security Utilities',
     'Kali security utility: python3-atomic-operator', 'approved_worker'),
    ('python3-dploot', 'Security Utilities',
     'Kali security utility: python3-dploot', 'approved_worker'),
    ('python3-ldapdomaindump', 'AI Security',
     'Kali security utility: python3-ldapdomaindump', 'approved_worker'),
    ('python3-pyinstaller', 'Security Utilities',
     'Kali security utility: python3-pyinstaller', 'approved_worker'),
    ('python3-wsgidav', 'Security Utilities',
     'Kali security utility: python3-wsgidav', 'approved_worker'),
    ('quark-engine', 'Security Utilities',
     'Kali security utility: quark-engine', 'approved_worker'),
    ('raven', 'Security Utilities', 'Kali security utility: raven', 'approved_worker'),
    ('reconspider', 'Attack Surface',
     'Kali security utility: reconspider', 'approved_worker'),
    ('redeye', 'Security Utilities',
     'Kali security utility: redeye', 'approved_worker'),
    ('redsnarf', 'Security Utilities',
     'Kali security utility: redsnarf', 'approved_worker'),
    ('rev-proxy-grapher', 'Security Utilities',
     'Kali security utility: rev-proxy-grapher', 'approved_worker'),
    ('ridenum', 'Security Utilities',
     'Kali security utility: ridenum', 'approved_worker'),
    ('rling', 'Security Utilities', 'Kali security utility: rling', 'approved_worker'),
    ('robotstxt', 'Security Utilities',
     'Kali security utility: robotstxt', 'approved_worker'),
    ('ropper', 'Reverse Engineering',
     'Kali security utility: ropper', 'approved_worker'),
    ('routersploit', 'Exploit Validation',
     'Kali security utility: routersploit', 'isolated_worker'),
    ('rubeus', 'Identity', 'Kali security utility: rubeus', 'isolated_worker'),
    ('ruby-pedump', 'Security Utilities',
     'Kali security utility: ruby-pedump', 'approved_worker'),
    ('s3scanner', 'Attack Surface',
     'Kali security utility: s3scanner', 'approved_worker'),
    ('sara', 'Security Utilities', 'Kali security utility: sara', 'approved_worker'),
    ('sentrypeer', 'Security Utilities',
     'Kali security utility: sentrypeer', 'isolated_worker'),
    ('sharphound', 'Identity', 'Kali security utility: sharphound', 'isolated_worker'),
    ('sharpshooter', 'Identity',
     'Kali security utility: sharpshooter', 'approved_worker'),
    ('shed', 'Security Utilities', 'Kali security utility: shed', 'approved_worker'),
    ('shell-gpt', 'Security Utilities',
     'Kali security utility: shell-gpt', 'approved_worker'),
    ('shellfire', 'Security Utilities',
     'Kali security utility: shellfire', 'approved_worker'),
    ('sherlock', 'Attack Surface', 'Kali security utility: sherlock', 'approved_worker'),
    ('sickle-pdk', 'Security Utilities',
     'Kali security utility: sickle-pdk', 'approved_worker'),
    ('sigma-cli', 'Threat Intelligence',
     'Kali security utility: sigma-cli', 'approved_worker'),
    ('silenttrinity', 'Security Utilities',
     'Kali security utility: silenttrinity', 'isolated_worker'),
    ('sippts', 'Security Utilities',
     'Kali security utility: sippts', 'approved_worker'),
    ('slimtoolkit', 'Security Utilities',
     'Kali security utility: slimtoolkit', 'approved_worker'),
    ('sliver', 'Security Utilities',
     'Kali security utility: sliver', 'isolated_worker'),
    ('sn0int', 'Security Utilities',
     'Kali security utility: sn0int', 'approved_worker'),
    ('snmpenum', 'Security Utilities',
     'Kali security utility: snmpenum', 'approved_worker'),
    ('snowdrop', 'Security Utilities',
     'Kali security utility: snowdrop', 'approved_worker'),
    ('sparrow-wifi', 'Wireless',
     'Kali security utility: sparrow-wifi', 'approved_worker'),
    ('spire', 'Security Utilities', 'Kali security utility: spire', 'approved_worker'),
    ('sploitscan', 'Security Utilities',
     'Kali security utility: sploitscan', 'approved_worker'),
    ('spray', 'Credential Audit', 'Kali security utility: spray', 'isolated_worker'),
    ('sprayhound', 'Credential Audit',
     'Kali security utility: sprayhound', 'isolated_worker'),
    ('sprayingtoolkit', 'Credential Audit',
     'Kali security utility: sprayingtoolkit', 'isolated_worker'),
    ('spraykatz', 'Credential Audit',
     'Kali security utility: spraykatz', 'isolated_worker'),
    ('sqlmc', 'Security Utilities', 'Kali security utility: sqlmc', 'approved_worker'),
    ('sshuttle', 'Security Utilities',
     'Kali security utility: sshuttle', 'approved_worker'),
    ('sslstrip', 'Security Utilities',
     'Kali security utility: sslstrip', 'isolated_worker'),
    ('sstimap', 'Security Utilities',
     'Kali security utility: sstimap', 'approved_worker'),
    ('stegcracker', 'Credential Audit',
     'Kali security utility: stegcracker', 'approved_worker'),
    ('subfinder', 'Attack Surface',
     'Kali security utility: subfinder', 'approved_worker'),
    ('subjack', 'Security Utilities',
     'Kali security utility: subjack', 'approved_worker'),
    ('sublist3r', 'Security Utilities',
     'Kali security utility: sublist3r', 'approved_worker'),
    ('syft', 'AppSec', 'Kali security utility: syft', 'approved_worker'),
    ('tailscale', 'AI Security', 'Kali security utility: tailscale', 'approved_worker'),
    ('teamsploit', 'Security Utilities',
     'Kali security utility: teamsploit', 'approved_worker'),
    ('terraform', 'Security Utilities',
     'Kali security utility: terraform', 'approved_worker'),
    ('testssl.sh', 'Web/API', 'Kali security utility: testssl.sh', 'approved_worker'),
    ('tetragon', 'Kubernetes', 'Kali security utility: tetragon', 'approved_worker'),
    ('tinja', 'Security Utilities', 'Kali security utility: tinja', 'approved_worker'),
    ('tookie-osint', 'Attack Surface',
     'Kali security utility: tookie-osint', 'approved_worker'),
    ('trivy', 'AppSec', 'Kali security utility: trivy', 'approved_worker'),
    ('trufflehog', 'AppSec', 'Kali security utility: trufflehog', 'approved_worker'),
    ('tundeep', 'Security Utilities',
     'Kali security utility: tundeep', 'approved_worker'),
    ('unblob', 'Reverse Engineering',
     'Kali security utility: unblob', 'approved_worker'),
    ('unhide.rb', 'Security Utilities',
     'Kali security utility: unhide.rb', 'approved_worker'),
    ('unicorn-magic', 'Security Utilities',
     'Kali security utility: unicorn-magic', 'approved_worker'),
    ('uro', 'Security Utilities', 'Kali security utility: uro', 'approved_worker'),
    ('vopono', 'Security Utilities',
     'Kali security utility: vopono', 'approved_worker'),
    ('vwifi-tool', 'Wireless', 'Kali security utility: vwifi-tool', 'approved_worker'),
    ('waybackpy', 'Security Utilities',
     'Kali security utility: waybackpy', 'approved_worker'),
    ('web-cache-vulnerability-scanner', 'Security Utilities',
     'Kali security utility: web-cache-vulnerability-scanner', 'approved_worker'),
    ('websploit', 'Security Utilities',
     'Kali security utility: websploit', 'isolated_worker'),
    ('wgetpaste', 'Security Utilities',
     'Kali security utility: wgetpaste', 'approved_worker'),
    ('whatmask', 'Security Utilities',
     'Kali security utility: whatmask', 'approved_worker'),
    ('wifiphisher', 'Wireless', 'Kali security utility: wifiphisher', 'isolated_worker'),
    ('wifipumpkin3', 'Wireless',
     'Kali security utility: wifipumpkin3', 'isolated_worker'),
    ('wig', 'Security Utilities', 'Kali security utility: wig', 'approved_worker'),
    ('wig-ng', 'Security Utilities',
     'Kali security utility: wig-ng', 'approved_worker'),
    ('witnessme', 'Security Utilities',
     'Kali security utility: witnessme', 'approved_worker'),
    ('wixl', 'Security Utilities', 'Kali security utility: wixl', 'approved_worker'),
    ('wmi-client', 'Security Utilities',
     'Kali security utility: wmi-client', 'approved_worker'),
    ('wordlistraider', 'AI Security',
     'Kali security utility: wordlistraider', 'approved_worker'),
    ('wotmate', 'Security Utilities',
     'Kali security utility: wotmate', 'approved_worker'),
    ('wpa-sycophant', 'Security Utilities',
     'Kali security utility: wpa-sycophant', 'approved_worker'),
    ('wpprobe', 'Security Utilities',
     'Kali security utility: wpprobe', 'approved_worker'),
    ('xsrfprobe', 'Web/API', 'Kali security utility: xsrfprobe', 'approved_worker'),
    ('xsstrike', 'Web/API', 'Kali security utility: xsstrike', 'approved_worker'),
    ('zonedb', 'Security Utilities',
     'Kali security utility: zonedb', 'approved_worker'),
    ('ADRecon', 'Identity', 'Advanced identity capability: ADRecon', 'approved_worker'),
    ('AI-SPM Connector', 'AI Security',
     'Advanced ai security capability: AI-SPM Connector', 'isolated_ai_worker'),
    ('ART', 'Security Utilities',
     'Advanced security utilities capability: ART', 'approved_worker'),
    ('AgentDojo', 'AI Security',
     'Advanced ai security capability: AgentDojo', 'isolated_ai_worker'),
    ('AgentWarden', 'AI Security',
     'Advanced ai security capability: AgentWarden', 'isolated_ai_worker'),
    ('Aircrack-ng', 'AI Security',
     'Advanced ai security capability: Aircrack-ng', 'isolated_ai_worker'),
    ('Airgeddon', 'AI Security',
     'Advanced ai security capability: Airgeddon', 'isolated_ai_worker'),
    ('Arjun', 'Web/API', 'Advanced web/api capability: Arjun', 'approved_worker'),
    ('Arkime', 'Network Discovery',
     'Advanced network discovery capability: Arkime', 'approved_worker'),
    ('BTLEJack', 'Wireless', 'Advanced wireless capability: BTLEJack', 'approved_worker'),
    ('Bettercap', 'Wireless', 'Advanced wireless capability: Bettercap', 'approved_worker'),
    ('BloodHound CE', 'Identity',
     'Advanced identity capability: BloodHound CE', 'isolated_worker'),
    ('BloodyAD', 'Identity', 'Advanced identity capability: BloodyAD', 'approved_worker'),
    ('CAPA', 'DFIR', 'Advanced dfir capability: CAPA', 'approved_worker'),
    ('Cartography', 'Cloud', 'Advanced cloud capability: Cartography', 'approved_worker'),
    ('Chainsaw', 'AI Security',
     'Advanced ai security capability: Chainsaw', 'isolated_ai_worker'),
    ('Cilium', 'Kubernetes', 'Advanced kubernetes capability: Cilium', 'approved_worker'),
    ('Cloud Custodian', 'Cloud',
     'Advanced cloud capability: Cloud Custodian', 'approved_worker'),
    ('CloudFox', 'Cloud', 'Advanced cloud capability: CloudFox', 'approved_worker'),
    ('CloudMapper', 'Cloud', 'Advanced cloud capability: CloudMapper', 'approved_worker'),
    ('CloudQuery', 'Cloud', 'Advanced cloud capability: CloudQuery', 'approved_worker'),
    ('Coercer', 'Identity', 'Advanced identity capability: Coercer', 'isolated_worker'),
    ('CyberSecEval', 'AI Security',
     'Advanced ai security capability: CyberSecEval', 'isolated_ai_worker'),
    ('CycloneDX CLI', 'AppSec',
     'Advanced appsec capability: CycloneDX CLI', 'approved_worker'),
    ('Dalfox', 'Web/API', 'Advanced web/api capability: Dalfox', 'approved_worker'),
    ('Datree', 'Security Utilities',
     'Advanced security utilities capability: Datree', 'approved_worker'),
    ('DeepEval', 'AI Security',
     'Advanced ai security capability: DeepEval', 'isolated_ai_worker'),
    ('DefectDojo', 'AppSec', 'Advanced appsec capability: DefectDojo', 'approved_worker'),
    ('Dependency-Track', 'AppSec',
     'Advanced appsec capability: Dependency-Track', 'approved_worker'),
    ('Eric Zimmerman Tools', 'DFIR',
     'Advanced dfir capability: Eric Zimmerman Tools', 'approved_worker'),
    ('Fickling', 'AI Security',
     'Advanced ai security capability: Fickling', 'isolated_ai_worker'),
    ('GNU Radio', 'Security Utilities',
     'Advanced security utilities capability: GNU Radio', 'approved_worker'),
    ('Giskard', 'AI Security',
     'Advanced ai security capability: Giskard', 'isolated_ai_worker'),
    ('Gitleaks', 'AppSec', 'Advanced appsec capability: Gitleaks', 'approved_worker'),
    ('Guardrails AI', 'AI Security',
     'Advanced ai security capability: Guardrails AI', 'isolated_ai_worker'),
    ('HTTPX', 'Web/API', 'Advanced web/api capability: HTTPX', 'approved_worker'),
    ('HackRF tools', 'Wireless',
     'Advanced wireless capability: HackRF tools', 'approved_worker'),
    ('Hayabusa', 'DFIR', 'Advanced dfir capability: Hayabusa', 'approved_worker'),
    ('Hostapd-MANA', 'Wireless',
     'Advanced wireless capability: Hostapd-MANA', 'approved_worker'),
    ('Hubble', 'Kubernetes', 'Advanced kubernetes capability: Hubble', 'approved_worker'),
    ('IAMGraph', 'Security Utilities',
     'Advanced security utilities capability: IAMGraph', 'approved_worker'),
    ('IVRE', 'Network Discovery',
     'Advanced network discovery capability: IVRE', 'approved_worker'),
    ('Inspect AI', 'AI Security',
     'Advanced ai security capability: Inspect AI', 'isolated_ai_worker'),
    ('Interactsh', 'Security Utilities',
     'Advanced security utilities capability: Interactsh', 'approved_worker'),
    ('Invariant', 'AI Security',
     'Advanced ai security capability: Invariant', 'isolated_ai_worker'),
    ('KAPE', 'DFIR', 'Advanced dfir capability: KAPE', 'approved_worker'),
    ('KICS', 'Cloud', 'Advanced cloud capability: KICS', 'approved_worker'),
    ('Katana', 'Web/API', 'Advanced web/api capability: Katana', 'approved_worker'),
    ('Kismet', 'Wireless', 'Advanced wireless capability: Kismet', 'approved_worker'),
    ('Kiterunner', 'Web/API', 'Advanced web/api capability: Kiterunner', 'approved_worker'),
    ('KubeLinter', 'Kubernetes',
     'Advanced kubernetes capability: KubeLinter', 'approved_worker'),
    ('LDAPDomainDump', 'AI Security',
     'Advanced ai security capability: LDAPDomainDump', 'isolated_ai_worker'),
    ('Langfuse', 'AI Security',
     'Advanced ai security capability: Langfuse', 'isolated_ai_worker'),
    ('LlamaFirewall', 'Security Utilities',
     'Advanced security utilities capability: LlamaFirewall', 'approved_worker'),
    ('MLflow', 'Security Utilities',
     'Advanced security utilities capability: MLflow', 'approved_worker'),
    ('MemProcFS', 'DFIR', 'Advanced dfir capability: MemProcFS', 'approved_worker'),
    ('ModelScan', 'AI Security',
     'Advanced ai security capability: ModelScan', 'isolated_ai_worker'),
    ('ModelScan CLI', 'AI Security',
     'Advanced ai security capability: ModelScan CLI', 'isolated_ai_worker'),
    ('NVIDIA NeMo Safety', 'AI Security',
     'Advanced ai security capability: NVIDIA NeMo Safety', 'isolated_ai_worker'),
    ('NetBox', 'Network Discovery',
     'Advanced network discovery capability: NetBox', 'approved_worker'),
    ('Netdisco', 'Network Discovery',
     'Advanced network discovery capability: Netdisco', 'approved_worker'),
    ('Ntop', 'Network Discovery',
     'Advanced network discovery capability: Ntop', 'approved_worker'),
    ('OSV-Scanner', 'AppSec', 'Advanced appsec capability: OSV-Scanner', 'approved_worker'),
    ('OWASP Amass', 'Attack Surface',
     'Advanced attack surface capability: OWASP Amass', 'approved_worker'),
    ('OWASP Dependency-Check', 'AppSec',
     'Advanced appsec capability: OWASP Dependency-Check', 'approved_worker'),
    ('OpenAI Evals', 'AI Security',
     'Advanced ai security capability: OpenAI Evals', 'isolated_ai_worker'),
    ('OpenSearch Security Analytics', 'Security Utilities',
     'Advanced security utilities capability: OpenSearch Security Analytics', 'approved_worker'),
    ('OpenTelemetry GenAI', 'AI Security',
     'Advanced ai security capability: OpenTelemetry GenAI', 'isolated_ai_worker'),
    ('Pacu', 'Cloud', 'Advanced cloud capability: Pacu', 'approved_worker'),
    ('Parliament', 'Cloud', 'Advanced cloud capability: Parliament', 'approved_worker'),
    ('Peirates', 'Kubernetes',
     'Advanced kubernetes capability: Peirates', 'approved_worker'),
    ('PetitPotam', 'Security Utilities',
     'Advanced security utilities capability: PetitPotam', 'isolated_worker'),
    ('Phoenix Arize', 'AI Security',
     'Advanced ai security capability: Phoenix Arize', 'isolated_ai_worker'),
    ('PingCastle', 'Identity',
     'Advanced identity capability: PingCastle', 'approved_worker'),
    ('Plaso', 'DFIR', 'Advanced dfir capability: Plaso', 'approved_worker'),
    ('Polaris', 'Security Utilities',
     'Advanced security utilities capability: Polaris', 'approved_worker'),
    ('Policy Sentry', 'Cloud',
     'Advanced cloud capability: Policy Sentry', 'approved_worker'),
    ('Principal Mapper', 'Cloud',
     'Advanced cloud capability: Principal Mapper', 'approved_worker'),
    ('ProjectDiscovery Cloud', 'Cloud',
     'Advanced cloud capability: ProjectDiscovery Cloud', 'approved_worker'),
    ('Protect AI', 'AI Security',
     'Advanced ai security capability: Protect AI', 'isolated_ai_worker'),
    ('Proxmark3', 'Wireless', 'Advanced wireless capability: Proxmark3', 'approved_worker'),
    ('Purple Knight', 'Identity',
     'Advanced identity capability: Purple Knight', 'approved_worker'),
    ('PyRIT', 'AI Security', 'Advanced ai security capability: PyRIT', 'isolated_ai_worker'),
    ('Rubeus', 'Identity', 'Advanced identity capability: Rubeus', 'isolated_worker'),
    ('Samba-tool', 'Security Utilities',
     'Advanced security utilities capability: Samba-tool', 'approved_worker'),
    ('ScoutSuite', 'Cloud', 'Advanced cloud capability: ScoutSuite', 'approved_worker'),
    ('Security Onion', 'Endpoint',
     'Advanced endpoint capability: Security Onion', 'approved_worker'),
    ('Semgrep AI rules', 'AI Security',
     'Advanced ai security capability: Semgrep AI rules', 'isolated_ai_worker'),
    ('SharpHound', 'Identity',
     'Advanced identity capability: SharpHound', 'isolated_worker'),
    ('Sigma CLI', 'Threat Intelligence',
     'Advanced threat intelligence capability: Sigma CLI', 'approved_worker'),
    ('Snyk CLI', 'AppSec', 'Advanced appsec capability: Snyk CLI', 'approved_worker'),
    ('Starboard', 'Security Utilities',
     'Advanced security utilities capability: Starboard', 'approved_worker'),
    ('Steampipe', 'Cloud', 'Advanced cloud capability: Steampipe', 'approved_worker'),
    ('Stratus Red Team', 'Cloud',
     'Advanced cloud capability: Stratus Red Team', 'approved_worker'),
    ('Tetragon', 'Kubernetes',
     'Advanced kubernetes capability: Tetragon', 'approved_worker'),
    ('The Sleuth Kit', 'DFIR',
     'Advanced dfir capability: The Sleuth Kit', 'approved_worker'),
    ('Timesketch', 'DFIR', 'Advanced dfir capability: Timesketch', 'approved_worker'),
    ('TruffleHog', 'AppSec', 'Advanced appsec capability: TruffleHog', 'approved_worker'),
    ('Ubertooth', 'Wireless', 'Advanced wireless capability: Ubertooth', 'approved_worker'),
    ('Wazuh', 'Endpoint', 'Advanced endpoint capability: Wazuh', 'approved_worker'),
    ('WiFi Explorer integration', 'Wireless',
     'Advanced wireless capability: WiFi Explorer integration', 'approved_worker'),
    ('WiFi Pineapple', 'Wireless',
     'Advanced wireless capability: WiFi Pineapple', 'approved_worker'),
    ('Wifite2', 'Wireless', 'Advanced wireless capability: Wifite2', 'isolated_worker'),
    ('YARA-X', 'DFIR', 'Advanced dfir capability: YARA-X', 'approved_worker'),
    ('ZMap', 'Network Discovery',
     'Advanced network discovery capability: ZMap', 'approved_worker'),
    ('kube-score', 'Kubernetes',
     'Advanced kubernetes capability: kube-score', 'approved_worker'),
    ('kubeaudit', 'Kubernetes',
     'Advanced kubernetes capability: kubeaudit', 'approved_worker'),
    ('ntopng', 'Network Discovery',
     'Advanced network discovery capability: ntopng', 'approved_worker'),
]

# Tools that must never be exposed as an unrestricted browser shell.
EXTENDED_PRIVILEGED_TOOLS = {

    'adaptixc2',
    'airgeddon',
    'bloodhound',
    'bloodhound-ce-python',
    'bloodhound.py',
    'bruteforce-luks',
    'bruteforce-salted-openssl',
    'bruteforce-wallet',
    'bruteshark',
    'brutespray',
    'chisel',
    'chisel-common-binaries',
    'cloudbrute',
    'coercer',
    'crackmapexec',
    'crowbar',
    'dnscat2',
    'donut',
    'evil-ssdp',
    'evilginx2',
    'fluxion',
    'golang-github-binject-go-donut',
    'gsocket',
    'havoc',
    'hoaxshell',
    'koadic',
    'ligolo-mp',
    'ligolo-ng',
    'ligolo-ng-common-binaries',
    'merlin-agent',
    'merlin-server',
    'metasploitmcp',
    'mitm6',
    'payloadsallthethings',
    'phishery',
    'phpggc',
    'phpsploit',
    'pocsuite3',
    'portspoof',
    'poshc2',
    'pwncat',
    'routersploit',
    'rubeus',
    'sentrypeer',
    'sharphound',
    'silenttrinity',
    'sliver',
    'spray',
    'sprayhound',
    'sprayingtoolkit',
    'spraykatz',
    'sslstrip',
    'websploit',
    'wifiphisher',
    'wifipumpkin3',
    'Aircrack-ng',
    'Airgeddon',
    'BloodHound CE',
    'Coercer',
    'PetitPotam',
    'Rubeus',
    'SharpHound',
    'Wifite2',
}


def build_tool_help(name: str, category: str, purpose: str, profile: str, privileged: bool) -> dict:
    """Create safe, per-tool education metadata for the UI.

    This deliberately explains purpose, workflow, evidence and governance rather
    than publishing attack recipes. It is generated for every catalog entry so a
    newly added tool cannot appear in the Marketplace without basic help text.
    """
    workflow = {
        "Network Discovery": "Define an owned/approved network scope, run discovery from the appropriate worker, validate hosts/services, then reconcile results with asset inventory.",
        "Attack Surface": "Start with an approved asset/domain list, prefer passive collection, validate ownership, then perform only the approved assessment stage.",
        "Web/API": "Select an authorized application, begin with mapping/passive checks, review findings, then use only the approved active assessment profile.",
        "Exploit Validation": "Use an isolated lab or explicitly approved validation worker. Confirm the suspected weakness and preserve evidence; do not use an unrestricted shell.",
        "Identity": "Use an approved directory or identity scope to map relationships, privilege paths and configuration weaknesses. Prioritize least privilege and MFA remediation.",
        "Identity/Network": "Use authorized identity/network telemetry to understand trust relationships and suspicious activity while preserving evidence.",
        "Credential Audit": "Use only authorized offline audit material or a dedicated lab. Treat credentials as secrets, minimize exposure, and record the audit scope.",
        "Wireless": "Use only networks you own/manage. Collect wireless metadata or approved lab evidence, compare against the trusted baseline, and preserve observations.",
        "Network Defense": "Inspect telemetry from networks you manage, identify anomalous protocols/flows, and turn validated observations into detections.",
        "Vulnerability": "Assess approved hosts, packages, images or applications; de-duplicate findings, map severity/KEV, and track remediation evidence.",
        "Cloud": "Use read-only or explicitly approved cloud access, inventory resources and permissions, identify exposure, then remediate through change control.",
        "Cloud/Container": "Assess images and workloads before deployment, correlate vulnerabilities with runtime exposure, and verify fixes in CI or an approved worker.",
        "Kubernetes": "Assess an approved cluster with least-privilege credentials, benchmark posture, inspect risky workloads/services, and preserve evidence.",
        "AppSec": "Run code analysis in CI or an approved worker, triage results, justify suppressions, and link remediation to commits/builds.",
        "IaC": "Scan approved infrastructure definitions before deployment; prioritize identity, public exposure, secrets and encryption controls.",
        "Endpoint": "Use the managed collector/agent on consented endpoints, collect telemetry, investigate anomalies, and avoid arbitrary remote execution.",
        "DFIR": "Acquire authorized artifacts, hash originals, analyze copies, preserve chain of custody, and record conclusions with confidence.",
        "Malware": "Analyze samples in isolated analysis workers, begin with static indicators/capabilities, and preserve hashes and evidence.",
        "Reverse Engineering": "Open a copy in an isolated workspace, inspect metadata/imports/strings/control flow, map behavior to detections, and preserve hashes.",
        "Firmware": "Analyze authorized firmware images offline, inventory components/configuration, identify exposed services, and document remediation.",
        "Forensics": "Extract metadata and recover relevant artifacts from authorized evidence copies without modifying the original evidence.",
        "Threat Intelligence": "Normalize indicators with source and confidence, correlate against internal telemetry, and keep attribution hypotheses separate from confirmed facts.",
        "Detection Engineering": "Create portable detections, test against known telemetry, measure false positives and coverage, and version-control the rule.",
        "AI Security": "Assess an approved AI application or agent for prompt/context integrity, tool authorization, RAG/data access, model supply chain and runtime telemetry.",
        "Security Utilities": "Use the tool for its documented supporting security task inside an approved worker, inspect output, and preserve relevant evidence.",
    }
    evidence = {
        "Network Discovery": ["hosts", "ports/services", "timestamps", "scope"],
        "Web/API": ["URLs/endpoints", "HTTP metadata", "alerts/findings", "timestamps"],
        "Identity": ["accounts", "relationships", "privilege paths", "configuration evidence"],
        "Cloud": ["resource IDs", "policy/configuration findings", "regions", "timestamps"],
        "AI Security": ["test case ID", "policy decision", "model/agent trace", "evidence hash"],
        "DFIR": ["artifact hash", "metadata", "timeline", "chain-of-custody reference"],
        "Malware": ["file hash", "static indicators", "capabilities", "analysis notes"],
    }
    return {
        "summary": purpose,
        "why_veyra": "Provides a governed, auditable entry point with role-based access, scope controls and normalized evidence.",
        "safe_workflow": workflow.get(category, workflow["Security Utilities"]),
        "expected_evidence": evidence.get(category, ["tool output", "target/scope", "timestamp", "provenance"]),
        "access": "Privileged Admin" if privileged else "Admin",
        "execution_boundary": profile,
        "common_mistakes": ["Using an asset outside the approved scope", "Treating tool output as proof without validation", "Ignoring evidence provenance or timestamps"],
        "next_step": "Validate the result, map it to VEYRA risk/graph/ATT&CK or ATLAS where applicable, remediate, and verify.",
        "help_boundary": "Educational and defensive guidance only; no credential attacks, payloads, persistence, C2, evasion or hack-back instructions."
    }


def extended_registry():
    """Return base + extended catalog with normalized governance metadata."""
    base = list(TOOL_REGISTRY)
    seen = {x[0] for x in base}
    rows = base + [x for x in EXTENDED_TOOL_REGISTRY if x[0] not in seen]
    privileged = set(PRIVILEGED_ADMIN_TOOLS) | EXTENDED_PRIVILEGED_TOOLS
    out = []
    used_ids = set()
    out = []
    for name, category, purpose, profile in rows:
        base_id = slugify(name)
        tool_id = base_id
        suffix = 2
        while tool_id in used_ids:
            tool_id = f"{base_id}-{suffix}"
            suffix += 1
        used_ids.add(tool_id)
        out.append({
            "id": tool_id,
            "name": name,
            "category": category,
            "purpose": purpose,
            "execution_profile": profile,
            "admin_only": True,
            "access_tier": "privileged_admin" if name in privileged else "admin",
            "privileged_usage": name in privileged,
            "browser_shell": False,
            "status": "cataloged",
            "source": "kali-2026.3.2-or-veyra-extension",
            "help": build_tool_help(name, category, purpose, profile, name in privileged),
        })
    return out


def install_manifest(tool: dict) -> dict:
    """Produce a managed-worker installation plan; does not install anything."""
    name = tool.get("name", "")
    # VEYRA uses package/artifact identifiers, not arbitrary user commands.
    package = slugify(name)
    return {
        "tool_id": tool.get("id"),
        "tool": name,
        "package_id": package,
        "platforms": ["kali-linux-amd64", "kali-linux-arm64"],
        "install_mode": "managed_worker",
        "source": "approved-package-source",
        "requires_admin": True,
        "requires_privileged_admin": bool(tool.get("privileged_usage")),
        "signed_artifact_required": True,
        "verification": ["source provenance", "artifact signature/hash", "version pin", "SBOM"],
        "note": "Installation is a worker-side operation. VEYRA SaaS never runs apt/pip/shell directly."
    }
