"""v4.0 tool supply-chain control plane tables"""
from alembic import op
import sqlalchemy as sa

revision='20260911_v40_supply_chain'
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('tool_definitions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('tool_id',sa.String(255),unique=True),sa.Column('name',sa.String(255)),sa.Column('category',sa.String(128)),sa.Column('purpose',sa.Text()),sa.Column('upstream_source',sa.String(128)),sa.Column('resolver_kind',sa.String(64)),sa.Column('maturity',sa.String(32)),sa.Column('update_channel',sa.String(32)),sa.Column('pin_mode',sa.String(32)),sa.Column('status',sa.String(32)),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)))
    op.create_table('tool_releases',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('release_id',sa.String(64),unique=True),sa.Column('tool_id',sa.String(255)),sa.Column('version',sa.String(128)),sa.Column('channel',sa.String(32)),sa.Column('artifact_uri',sa.Text()),sa.Column('artifact_digest',sa.String(160)),sa.Column('artifact_sha256',sa.String(64)),sa.Column('signature',sa.Text()),sa.Column('signature_required',sa.Boolean()),sa.Column('provenance_uri',sa.Text()),sa.Column('provenance_required',sa.Boolean()),sa.Column('sbom_uri',sa.Text()),sa.Column('sbom_required',sa.Boolean()),sa.Column('license',sa.String(128)),sa.Column('source_commit',sa.String(128)),sa.Column('verification_status',sa.String(32)),sa.Column('verification_errors',sa.Text()),sa.Column('health_status',sa.String(32)),sa.Column('notes',sa.Text()),sa.Column('discovered_at',sa.DateTime(timezone=True)))
    op.create_table('tool_artifacts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('artifact_id',sa.String(64),unique=True),sa.Column('release_id',sa.String(64)),sa.Column('storage_uri',sa.Text()),sa.Column('digest',sa.String(160)),sa.Column('sha256',sa.String(64)),sa.Column('signature_status',sa.String(32)),sa.Column('provenance_status',sa.String(32)),sa.Column('sbom_status',sa.String(32)),sa.Column('immutable',sa.Boolean()),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_table('tool_update_policies',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('policy_id',sa.String(64),unique=True),sa.Column('tool_id',sa.String(255),unique=True),sa.Column('channel',sa.String(32)),sa.Column('pin_mode',sa.String(32)),sa.Column('pinned_version',sa.String(128)),sa.Column('pinned_digest',sa.String(160)),sa.Column('auto_update',sa.Boolean()),sa.Column('critical_override',sa.Boolean()),sa.Column('require_canary',sa.Boolean()),sa.Column('canary_percent',sa.Integer()),sa.Column('maintenance_window',sa.String(128)),sa.Column('freeze_reason',sa.Text()),sa.Column('frozen_until',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)))
    op.create_table('tool_deployments',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('deployment_id',sa.String(64),unique=True),sa.Column('tool_id',sa.String(255)),sa.Column('release_id',sa.String(64)),sa.Column('worker_id',sa.String(128)),sa.Column('operation',sa.String(32)),sa.Column('target_version',sa.String(128)),sa.Column('state',sa.String(32)),sa.Column('force',sa.Boolean()),sa.Column('manifest_json',sa.Text()),sa.Column('manifest_sha256',sa.String(64)),sa.Column('worker_receipt_json',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('tool_health_checks',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('check_id',sa.String(64),unique=True),sa.Column('release_id',sa.String(64)),sa.Column('worker_id',sa.String(128)),sa.Column('status',sa.String(32)),sa.Column('checks_json',sa.Text()),sa.Column('evidence_sha256',sa.String(64)),sa.Column('notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('agent_containment_policies',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('policy_id',sa.String(64),unique=True),sa.Column('name',sa.String(255)),sa.Column('egress_mode',sa.String(32)),sa.Column('allowed_destinations_json',sa.Text()),sa.Column('service_account_velocity_threshold',sa.Integer()),sa.Column('website_collaboration_detection',sa.Boolean()),sa.Column('emergency_stop',sa.Boolean()),sa.Column('require_human_approval_for_external_action',sa.Boolean()),sa.Column('updated_at',sa.DateTime(timezone=True)))

def downgrade():
    for t in ['agent_containment_policies','tool_health_checks','tool_deployments','tool_update_policies','tool_artifacts','tool_releases','tool_definitions']:
        op.drop_table(t)
