import React,{useEffect,useState} from 'react';
import {Panel} from './v29_components.jsx';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('aegisx_user_token')}`,'Content-Type':'application/json'});
const get=path=>fetch(`${API}${path}`,{headers:auth()}).then(r=>{if(!r.ok)throw new Error(`${r.status}`);return r.json()});
function Shell({title,eyebrow,children}){return <div className="content"><div className="sectionintro"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div></div>{children}</div>}
export function V3FabricView(){const[d,setD]=useState(null);useEffect(()=>{get('/api/v3/fabric/overview').then(setD).catch(()=>{})},[]);return <Shell title="Full Security Operations Fabric" eyebrow="VEYRA V3.0 · UNIFIED SOC">{!d?<div className="empty">Loading fabric telemetry…</div>:<><div className="grid3">{Object.entries(d.posture).map(([k,v])=><div className="card" key={k}><small>{k.replaceAll('_',' ')}</small><strong>{v}</strong></div>)}</div><Panel title="Incident lifecycle"><div style={{padding:18,display:'flex',gap:8,flexWrap:'wrap'}}>{d.pipeline.map((x,i)=><span className="badge" key={x}>{i+1}. {x}</span>)}</div></Panel><Panel title="Priority queue"><div className="table">{d.priority_queue.map((x,i)=><div className="row" key={i}><div><b>{x.type.toUpperCase()} · {x.title}</b><small>{x.asset||`asset ${x.asset_id||'—'}`}</small></div><span className={'badge '+(x.severity==='CRITICAL'||x.risk>=80?'critical':'')}>{x.severity} · {Math.round(x.risk||0)}</span></div>)}{!d.priority_queue.length&&<div className="empty">No priority items.</div>}</div></Panel><div className="callout"><b>Control plane:</b> containment is approval-gated, attribution is hypothesis-only, and third-party tooling executes only on managed workers.</div></>}</Shell>}
export function V3GraphView(){const[d,setD]=useState(null);useEffect(()=>{get('/api/v3/fabric/graph').then(setD).catch(()=>{})},[]);return <Shell title="Unified Security Graph" eyebrow="V3.0 · GRAPH FUSION">{!d?<div className="empty">Loading graph…</div>:<><div className="grid3"><div className="card"><small>NODES</small><strong>{d.nodes.length}</strong></div><div className="card"><small>EDGES</small><strong>{d.edges.length}</strong></div><div className="card"><small>ENTITY TYPES</small><strong>{d.legend.length}</strong></div></div><Panel title="Graph entities"><div className="table">{d.nodes.slice(0,80).map(x=><div className="row" key={x.id}><div><b>{x.label}</b><small>{x.type} · {x.id}</small></div><span className={'badge '+(x.risk>=80?'critical':'')}>RISK {Math.round(x.risk||0)}</span></div>)}</div></Panel><div className="callout">The graph is a correlation/read model. VEYRA does not infer causality from a single edge.</div></>}</Shell>}
export function V3ReconstructionView(){const[d,setD]=useState(null);useEffect(()=>{get('/api/v3/fabric/reconstruction?limit=100').then(setD).catch(()=>{})},[]);return <Shell title="AI Attack Reconstruction" eyebrow="V3.0 · RECONSTRUCTION">{!d?<div className="empty">Loading reconstruction…</div>:<><Panel title="Correlated event chain"><div className="table">{d.events.map((x,i)=><div className="row" key={i}><div><b>{x.stage.toUpperCase()} · {x.actor} → {x.target}</b><small>{String(x.time).slice(0,19).replace('T',' ')} · {x.source} · {x.detail}</small></div><span className={'badge '+(x.risk>=80?'critical':'')}>{Math.round(x.risk||0)}</span></div>)}{!d.events.length&&<div className="empty">No correlated events yet.</div>}</div></Panel><div className="callout">{d.warning}</div></>}</Shell>}
export function V3AIInvestigationView(){const[d,setD]=useState(null);useEffect(()=>{get('/api/v3/fabric/ai-investigation').then(setD).catch(()=>{})},[]);return <Shell title="AI SOC Investigator" eyebrow="V3.0 · AGENTIC INVESTIGATION">{!d?<div className="empty">Loading investigator…</div>:<><Panel title="Priority signals"><div className="table">{d.signals.map(x=><div className="row" key={x.signal}><div><b>{x.signal.replaceAll('_',' ')}</b><small>Observed count: {x.count}</small></div><span className={'badge '+(x.priority>=85?'critical':'')}>P{x.priority}</span></div>)}{!d.signals.length&&<div className="empty">No elevated signals.</div>}</div></Panel><Panel title="Reasoning contract"><div style={{padding:16}}><ol>{d.reasoning_steps.map(x=><li key={x} style={{margin:'8px 0'}}>{x}</li>)}</ol></div></Panel><div className="callout"><b>Guardrails:</b> {d.guardrails.join(' · ')}</div></>}</Shell>}
export function V3ResponseView(){const[d,setD]=useState(null),[msg,setMsg]=useState('');const stage=()=>{setMsg('');fetch(`${API}/api/v3/fabric/response-plan`,{method:'POST',headers:auth(),body:JSON.stringify({})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.detail||'Unable to stage plan');setD(j);setMsg('Governed response plan staged. No containment action was executed.')}).catch(e=>setMsg(e.message))};return <Shell title="Governed Response & Recovery" eyebrow="V3.0 · SOAR CONTROL">{msg&&<div className="callout">{msg}</div>}<Panel title="Response plan"><div style={{padding:16}}><button className="primary" onClick={stage}>Stage response plan</button></div>{d?.actions&&<div className="table">{d.actions.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.mode} · verification: {x.verification}</small></div><span className={'badge '+(x.approval==='required'?'critical':'')}>{x.approval}</span></div>)}</div>}</Panel><Recovery/></Shell>}
function Recovery(){const[d,setD]=useState(null);useEffect(()=>{get('/api/v3/fabric/recovery').then(setD).catch(()=>{})},[]);return <Panel title="Recovery verification"><div className="table">{d?.checks?.map(x=><div className="row" key={x.name}><div><b>{x.name.replaceAll('_',' ')}</b><small>Observed: {x.value}</small></div><span className={'badge '+(!x.pass?'critical':'')}>{x.pass?'PASS':'REVIEW'}</span></div>)}</div>{d&&<div className="callout"><b>Overall:</b> {d.overall}. {d.note}</div>}</Panel>}
