import React,{useEffect,useState} from 'react';
import {Panel} from './v29_components.jsx';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('aegisx_user_token')}`});
export function V37SecurityGraphIntelligenceView(){
 const [d,setD]=useState(null),[ev,setEv]=useState(null),[tab,setTab]=useState('overview');
 useEffect(()=>{Promise.all([fetch(`${API}/api/v37/security-graph/intelligence`,{headers:auth()}).then(r=>r.json()),fetch(`${API}/api/v37/security-graph/control-evidence`,{headers:auth()}).then(r=>r.json())]).then(([a,b])=>{setD(a);setEv(b)}).catch(()=>{})},[]);
 const inv=d?.inventory||{}, controls=d?.controls||[];
 return <div className="content"><div className="sectionintro"><div><div className="eyebrow">VEYRA V3.7 · SECURITY GRAPH INTELLIGENCE</div><h2>Unified Security Graph Intelligence</h2><p>Correlate assets, identities, cloud resources, AI systems, findings, incidents and evidence into an explainable operating view. This layer is read-only; authorization and containment remain governed.</p></div><div style={{display:'flex',gap:8}}><button className={tab==='overview'?'primary':''} onClick={()=>setTab('overview')}>Graph</button><button className={tab==='controls'?'primary':''} onClick={()=>setTab('controls')}>Controls & evidence</button></div></div>
 <div className="grid3"><div className="card"><small>GRAPH NODES</small><strong style={{fontSize:22}}>{d?.graph?.nodes??'—'}</strong></div><div className="card"><small>RELATIONSHIPS</small><strong style={{fontSize:22}}>{d?.graph?.edges??'—'}</strong></div><div className="card"><small>ATTACK PATHS</small><strong style={{fontSize:22}}>{d?.attack_paths?.length??'—'}</strong></div></div>
 {tab==='overview'?<><Panel title="Graph hotspots"><div className="table">{(d?.hotspots||[]).map(x=><div className="row" key={x.node}><div><b>{x.label}</b><small>{x.kind} · {x.connections} connections</small></div><span className={'badge '+(x.risk_score>=70?'critical':'')}>risk {x.risk_score}</span></div>)}{!d?.hotspots?.length&&<div className="empty">No graph relationships yet.</div>}</div></Panel><Panel title="Chokepoints & attack paths"><div className="table">{(d?.chokepoints||[]).map(x=><div className="row" key={x.node}><div><b>{x.label}</b><small>Appears on {x.paths} correlated paths</small></div><span className="badge">CHOKEPOINT</span></div>)}{(d?.attack_paths||[]).map((p,i)=><div className="row" key={i}><div><b>{p.target_label}</b><small>Path length {p.length} · risk {p.risk}</small><small>{p.steps.map(s=>`${s.from} → ${s.to}`).join(' · ')}</small></div><span className="badge">PATH</span></div>)}</div></Panel></>:<><Panel title="Control coverage"><div className="table">{controls.map(c=><div className="row" key={c.id}><div><b>{c.name}</b><small>{c.references.join(' · ')}</small></div><span className={'badge '+(c.status==='attention'?'critical':'')}>{c.status.toUpperCase()}</span></div>)}</div></Panel><Panel title="Evidence receipts"><div className="table">{(ev?.evidence_receipts||[]).map(x=><div className="row" key={x.artifact_id}><div><b>{x.artifact_id}</b><small>{x.source} · {x.result_type} · {x.classification}</small><small>job {x.job_id} · SHA-256 {x.sha256}</small></div><span className="badge">RECEIPT</span></div>)}{!ev?.evidence_receipts?.length&&<div className="empty">No evidence receipts yet.</div>}</div></Panel></>}
 {d?.drift_signals?.length>0&&<div className="callout"><b>Drift signals:</b> {d.drift_signals.map(x=>x.reason).join(' ')}</div>}
 <div className="callout"><b>AI rule:</b> AI explanations may prioritize and summarize graph relationships, but the underlying relationship, finding, control and evidence records remain the authoritative inputs. No autonomous destructive response is exposed here.</div></div>
}
