import React,{useEffect,useState} from 'react';
import {Panel} from './v29_components.jsx';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('VEYRA_user_token')}`,'Content-Type':'application/json'});
export function V39AutonomousExposureValidationView(){
 const [d,setD]=useState(null),[cases,setCases]=useState([]),[agent,setAgent]=useState(''),[result,setResult]=useState(null),[msg,setMsg]=useState('');
 const load=()=>Promise.all([fetch(`${API}/api/v39/exposure/overview`,{headers:auth()}).then(r=>r.json()),fetch(`${API}/api/v39/rogue-agents/cases`,{headers:auth()}).then(r=>r.json())]).then(([a,b])=>{setD(a);setCases(b.cases||[])}).catch(e=>setMsg(e.message));
 useEffect(load,[]);
 const investigate=async()=>{setMsg('');setResult(null);if(!agent.trim())return setMsg('Enter an enrolled/observed agent identity.');try{const r=await fetch(`${API}/api/v39/rogue-agents/investigate`,{method:'POST',headers:auth(),body:JSON.stringify({agent_id:agent.trim()})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'investigation failed');setResult(j);load()}catch(e){setMsg(e.message)}};
 const s=d?.risk_summary||{};
 return <div className="content">
  <div className="sectionintro"><div><div className="eyebrow">VEYRA V3.9 · AUTONOMOUS EXPOSURE VALIDATION FABRIC</div><h2>AI Security Research Lab</h2><p>Continuously fingerprint managed assets, correlate vulnerabilities and identities, detect anomalous agent behavior, reconstruct the evidence-backed timeline, and stage safe containment. Deterministic telemetry remains authoritative.</p></div></div>
  {msg&&<div className="callout">{msg}</div>}
  <div className="grid3"><div className="card"><small>ROGUE AGENT CANDIDATES</small><strong style={{fontSize:22}}>{s.critical_agent_candidates??0}</strong></div><div className="card"><small>VULNERABLE ENDPOINTS</small><strong style={{fontSize:22}}>{s.vulnerable_endpoints??0}</strong></div><div className="card"><small>AGENT RUNTIME EVENTS</small><strong style={{fontSize:22}}>{d?.counts?.agent_events??0}</strong></div></div>
  <Panel title="Rogue-agent detection signals"><div className="table">{(d?.rogue_agent_candidates||[]).map(x=><div className="row" key={x.agent_id}><div><b>{x.agent_id}</b><small>{x.events} events · {x.first_seen} → {x.last_seen}</small><small>{x.reasons.join(' · ')||'No high-confidence anomaly reason recorded'}</small></div><span className={'badge '+(x.score>=70?'critical':'')}>{x.score}/100</span></div>)}{!d?.rogue_agent_candidates?.length&&<div className="empty">No agent-runtime anomalies are currently recorded.</div>}</div></Panel>
  <Panel title="Investigate an agent"><div style={{display:'flex',gap:8,padding:14}}><input style={{flex:1}} value={agent} onChange={e=>setAgent(e.target.value)} placeholder="agent_id from runtime telemetry"/><button className="primary" onClick={investigate}>Investigate</button></div>{result&&<div style={{padding:16}}><div className="callout"><b>Case {result.case_id}</b> · confidence {Math.round((result.confidence||0)*100)}% · evidence SHA-256 {result.evidence_sha256}</div><h4>Root-cause hypothesis</h4><p>{result.root_cause}</p><h4>Timeline</h4><div className="table">{(result.timeline||[]).map((x,i)=><div className="row" key={i}><div><b>{x.operation} · {x.tool||'no-tool'}</b><small>{x.created_at} · trace {x.trace_id}</small></div><span className="badge">risk {x.risk}</span></div>)}</div><h4>Suggested containment sequence</h4><ol style={{color:'#9eb8d4',fontSize:11,lineHeight:1.8}}>{(result.containment_plan||[]).map(x=><li key={x.step}><b>{x.action}:</b> {x.detail}</li>)}</ol></div>}</Panel>
  <div className="grid2"><Panel title="Endpoint exposure"><div className="table">{(d?.endpoint_exposure||[]).map(x=><div className="row" key={x.hostname}><div><b>{x.hostname}</b><small>{x.os} · {x.ip} · last seen {x.last_seen}</small></div><span className={'badge '+(x.critical||x.kev?'critical':'')}>{x.critical} critical · {x.kev} KEV</span></div>)}</div></Panel><Panel title="Identity anomalies"><div className="table">{(d?.identity_anomalies||[]).slice(0,25).map((x,i)=><div className="row" key={i}><div><b>{x.username}</b><small>{x.source_ip} → asset {x.asset_id} · {x.application}</small></div><span className="badge">{Math.round((x.anomaly_score||0)*100)}%</span></div>)}</div></Panel></div>
  <Panel title="How VEYRA determines whether an agent is rogue"><div style={{padding:16}}><ol style={{color:'#9eb8d4',fontSize:11,lineHeight:1.8}}><li><b>Identify:</b> map agent identity, owner, provider/model, endpoint and credentials.</li><li><b>Baseline:</b> compare tool calls, operations, destinations, timing and delegation against the registered policy.</li><li><b>Correlate:</b> join agent traces with user sessions, endpoint findings, network flows, cloud/Kubernetes relationships and evidence.</li><li><b>Reconstruct:</b> establish first seen, initial access hypothesis, credential use, lateral movement and impact only where telemetry supports it.</li><li><b>Contain:</b> preserve evidence first, then stage credential/session revocation, endpoint isolation, tool/MCP/A2A trust reduction and patching for human approval.</li><li><b>Prove:</b> re-run independent validation and capture fresh evidence. A closed ticket alone is not proof.</li></ol></div></Panel>
  <Panel title="Security boundary"><div className="callout"><b>No autonomous offensive action.</b> The Research Lab may analyze authorized targets, prioritize hypotheses and stage deterministic validation. It does not expose credential theft, persistence, arbitrary shell execution, exploit delivery, destructive actions or hack-back. Existing approval-gated worker/SOAR controls remain the only route to permitted response.</div></Panel>
 </div>
}
