import React,{useEffect,useState} from 'react';
import {Panel} from './v29_components.jsx';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('VEYRA_user_token')}`,'Content-Type':'application/json'});
export function V42TrustedSupplyChainView(){
 const [o,setO]=useState(null),[assets,setAssets]=useState([]),[breakers,setBreakers]=useState([]),[msg,setMsg]=useState('');
 const [agent,setAgent]=useState(''),[reason,setReason]=useState(''),[ai,setAi]=useState({asset_id:'',asset_type:'model',name:'',version:'',digest:'',source_uri:'',provenance_uri:'',sbom_uri:''});
 const load=async()=>{try{const [a,b,c]=await Promise.all([fetch(`${API}/api/v42/trusted-supply-chain/overview`,{headers:auth()}),fetch(`${API}/api/v42/ai-supply-chain/assets`,{headers:auth()}),fetch(`${API}/api/v42/agent-circuit-breakers`,{headers:auth()})]);if(a.ok)setO(await a.json());if(b.ok)setAssets(await b.json());if(c.ok)setBreakers(await c.json())}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const stop=async()=>{const r=await fetch(`${API}/api/v42/agent-circuit-breaker`,{method:'POST',headers:auth(),body:JSON.stringify({agent_id:agent,reason,scope:'agent'})});const j=await r.json();setMsg(r.ok?`Circuit breaker ${j.breaker_id} armed.`:(j.detail||'failed'));load()};
 const addAI=async()=>{const r=await fetch(`${API}/api/v42/ai-supply-chain/assets`,{method:'POST',headers:auth(),body:JSON.stringify(ai)});const j=await r.json();setMsg(r.ok?`AI asset ${j.asset_id} registered.`:(j.detail||'failed'));load()};
 return <div className="content"><div className="sectionintro"><div><div className="eyebrow">VEYRA V4.2 · TRUSTED SUPPLY CHAIN</div><h2>Trusted Supply Chain Fabric</h2><p>Identity → provenance → integrity → policy → validation → controlled deployment → runtime observability. Existence is never trust.</p></div></div>{msg&&<div className="callout">{msg}</div>}
 <div className="grid3">{[['Attestations',o?.attestations],['Canary cohorts',o?.canary_cohorts],['AI supply-chain assets',o?.ai_supply_chain_assets],['Armed circuit breakers',o?.armed_circuit_breakers]].map(x=><div className="card" key={x[0]}><strong style={{fontSize:22}}>{x[1]??'—'}</strong><small>{x[0]}</small></div>)}</div>
 <Panel title="VEYRA trust invariant"><div style={{padding:16}}><p style={{fontSize:16,lineHeight:1.8,color:'#d9e7f7'}}>{o?.trust_invariant||'—'}</p></div></Panel>
 <Panel title="Trusted verification gates"><div className="grid3" style={{padding:16}}>{(o?.gates||[]).map(g=><div className="card" key={g}><b>{g.replaceAll('_',' ')}</b><small>required evidence</small></div>)}</div></Panel>
 <div className="grid2"><Panel title="AI / MCP / agent supply-chain inventory"><div style={{padding:16,display:'grid',gap:8}}><input value={ai.asset_id} onChange={e=>setAi({...ai,asset_id:e.target.value})} placeholder="asset_id"/><select value={ai.asset_type} onChange={e=>setAi({...ai,asset_type:e.target.value})}><option>model</option><option>agent</option><option>mcp_server</option><option>a2a_service</option><option>dataset</option><option>prompt_package</option></select><input value={ai.name} onChange={e=>setAi({...ai,name:e.target.value})} placeholder="name"/><input value={ai.version} onChange={e=>setAi({...ai,version:e.target.value})} placeholder="version"/><input value={ai.digest} onChange={e=>setAi({...ai,digest:e.target.value})} placeholder="immutable digest"/><input value={ai.provenance_uri} onChange={e=>setAi({...ai,provenance_uri:e.target.value})} placeholder="provenance URI"/><input value={ai.sbom_uri} onChange={e=>setAi({...ai,sbom_uri:e.target.value})} placeholder="SBOM / AIBOM URI"/><button className="primary" onClick={addAI}>Register AI supply-chain asset</button></div></Panel>
 <Panel title="Agent emergency circuit breaker"><div style={{padding:16,display:'grid',gap:8}}><input value={agent} onChange={e=>setAgent(e.target.value)} placeholder="agent identity"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="reason"/><button className="primary" onClick={stop}>Arm external kill path</button><small>This creates a control-plane containment record. Actual network/identity enforcement belongs to the managed enforcement plane.</small></div></Panel></div>
 <Panel title="Registered AI supply-chain assets"><div className="table">{assets.map(a=><div className="row" key={a.asset_id}><div><b>{a.name}</b><small>{a.asset_type} · {a.version} · {a.asset_id}</small><small>digest {a.digest||'not registered'} · provenance {a.provenance_uri?'present':'missing'} · SBOM {a.sbom_uri?'present':'missing'}</small></div><span className="badge">{a.trust_status}</span></div>)}{!assets.length&&<div className="empty">No AI supply-chain assets registered yet.</div>}</div></Panel>
 <Panel title="Agent circuit breakers"><div className="table">{breakers.map(b=><div className="row" key={b.breaker_id}><div><b>{b.agent_id}</b><small>{b.scope} · {b.reason}</small></div><span className={'badge '+(b.state==='armed'?'critical':'')}>{b.state}</span></div>)}{!breakers.length&&<div className="empty">No emergency circuit breakers are armed.</div>}</div></Panel>
 <Panel title="Production integrations"><div className="grid3" style={{padding:16}}>{Object.entries(o?.integrations||{}).map(([k,v])=><div className="card" key={k}><b>{k.toUpperCase()}</b><small>{v.status}</small><small>{v.purpose||v.version||''}</small></div>)}</div></Panel>
 </div>
}
