import React,{useEffect,useState} from 'react';
import {ShieldCheck,Network,Bot,Brain,GitBranch,PauseCircle,CheckCircle2,AlertTriangle,KeyRound,Waypoints,Database,Receipt,Activity,Box} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function Panel({title,children}){return <section className="panel"><div className="panelhead"><b>{title}</b><ShieldCheck size={16}/></div>{children}</section>}
const gates=['identity','provenance','integrity','policy_compliance','validation','deployment_control','runtime_attestation','behavioral_baseline','trajectory_assurance','evidence_integrity','circuit_breaker_readiness'];
export function V50AutonomousSecurityControlPlane(){
 const [o,setO]=useState(null),[assets,setAssets]=useState([]),[decisions,setDecisions]=useState([]),[msg,setMsg]=useState('');
 const [asset,setAsset]=useState({asset_id:'demo-agent',asset_type:'agent',name:'Demo Agent',version:'1.0.0',digest:'',publisher:'',provenance_uri:'',policy_status:'pending',validation_status:'pending',deployment_status:'pending',behavior_baseline:'',trajectory_policy:'',evidence_sha256:''});
 const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('aegisx_user_token')}`,'Content-Type':'application/json'});
 const load=async()=>{const [a,b,c]=await Promise.all([fetch(`${API}/api/v50/overview`,{headers:auth()}),fetch(`${API}/api/v50/ai-assets`,{headers:auth()}),fetch(`${API}/api/v50/decisions`,{headers:auth()})]);if(a.ok)setO(await a.json());if(b.ok)setAssets(await b.json());if(c.ok)setDecisions(await c.json())};
 useEffect(()=>{load()},[]);
 const register=async()=>{setMsg('');const r=await fetch(`${API}/api/v50/ai-assets/register`,{method:'POST',headers:auth(),body:JSON.stringify(asset)});const j=await r.json();setMsg(r.ok?`Asset ${j.asset} → ${j.evaluation.status} (${j.evaluation.score}%). Missing: ${j.evaluation.missing.join(', ')||'none'}`:(j.detail||'Registration failed'));load()};
 return <div className="content">
  <div className="sectionintro"><div><div className="eyebrow">VEYRA v5.0 · AUTONOMOUS SECURITY CONTROL PLANE</div><h2>Continuous trust, not implicit trust</h2><p>v4.0–v4.4 capabilities converge into one governed trust plane for tools, models, agents, MCP, A2A, workloads, data and runtime behavior.</p></div><span className="badge">5.0.0</span></div>
  <Panel title="The VEYRA trust invariant"><div className="callout"><b>{o?.trust_invariant||'No asset becomes trusted merely because it exists.'}</b><br/><small>Registration is inventory. Trust is earned through identity, provenance, integrity, policy, validation, controlled deployment, runtime evidence and recovery readiness.</small></div></Panel>
  <div className="grid2"><Panel title="Trust gates"><div className="table">{(o?.gates||gates).map((g,i)=><div className="row" key={g}><div><b>{i+1}. {g.replaceAll('_',' ')}</b><small>Mandatory control-plane gate</small></div><span className="badge">REQUIRED</span></div>)}</div></Panel><Panel title="Control modes"><div className="table">{['observe','approval_required','enforce','emergency_stop'].map((x,i)=><div className="row" key={x}><div><b>{x.replaceAll('_',' ').toUpperCase()}</b><small>{i===0?'Telemetry only':i===1?'Human authorization boundary':i===2?'Managed policy enforcement':'Immediate containment boundary'}</small></div><span className="badge">CONTROL</span></div>)}</div></Panel></div>
  <Panel title="AI / Agent Supply Chain Registry"><div style={{padding:14,display:'grid',gap:8,gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))'}}>{Object.entries(asset).map(([k,v])=><input key={k} value={v} onChange={e=>setAsset({...asset,[k]:e.target.value})} placeholder={k}/>)}<button className="primary" onClick={register}>Register + evaluate trust</button></div>{msg&&<div className="callout">{msg}</div>}<div className="table">{assets.map(a=><div className="row" key={a.asset_id}><div><b>{a.name}</b><small>{a.asset_id} · {a.asset_type} · {a.version}</small><small>{a.digest||'No immutable digest'}</small></div><span className={a.trust_status==='trusted'?'badge':'badge critical'}>{a.trust_status}</span></div>)}{!assets.length&&<div className="empty">No v5 AI supply-chain assets registered.</div>}</div></Panel>
  <div className="grid2"><Panel title="Trajectory assurance"><div className="callout"><Bot size={15}/> Individual tool calls are not sufficient evidence. VEYRA evaluates the full agent trajectory for tool, identity, destination, approval and delegation consistency.</div><div className="row"><div><b>Trajectory-with-evidence</b><small>Hash-chained decision evidence is expected at the enforcement boundary.</small></div><span className="badge">RUNTIME CONTRACT</span></div></Panel><Panel title="Unified Trust Graph"><div className="callout"><GitBranch size={15}/> Links model → wrapper → prompt → agent → MCP → tool → identity → endpoint → network → data → action.</div><div className="row"><div><b>{o?.graph_nodes??0} graph nodes</b><small>Trust propagates through relationships; a compromised dependency can reduce downstream trust.</small></div><span className="badge">GRAPH</span></div></Panel></div>
  <Panel title="Trust decisions"><div className="table">{decisions.map(d=><div className="row" key={d.decision_id}><div><b>{d.subject_id}</b><small>{d.decision_id} · {d.reason}</small><small>Evidence {d.evidence_sha256?.slice(0,24)}…</small></div><span className={d.decision==='allow'?'badge':'badge critical'}>{d.decision}</span></div>)}{!decisions.length&&<div className="empty">No trust decisions recorded.</div>}</div></Panel>
  <div className="grid2">
   <Panel title="Agent Identity & Authority Plane"><div className="callout"><KeyRound size={15}/> Cryptographic agent identity, owner, delegated authority, expiration and revocation are treated as first-class trust objects.</div><div className="row"><div><b>Authority before autonomy</b><small>Identity → delegated authority → tool/resource authority → action authority.</small></div><span className="badge">AIP</span></div></Panel>
   <Panel title="Agent Gateway"><div className="callout"><Waypoints size={15}/> Tool/API/MCP/A2A requests should cross a governed enforcement point for identity, policy, DLP, egress, approval and transaction limits.</div><div className="row"><div><b>Zero direct trust</b><small>VEYRA issues the decision; the managed gateway enforces it.</small></div><span className="badge">GATEWAY</span></div></Panel>
  </div>
  <div className="grid2">
   <Panel title="MCP Rug-Pull Detection"><div className="callout"><Box size={15}/> Fingerprints server version, tools, permissions and endpoints. Changes can become approval-required or quarantine candidates.</div><div className="row"><div><b>Tool poisoning / permission drift</b><small>Compare trusted baseline with observed MCP metadata.</small></div><span className="badge">DRIFT</span></div></Panel>
   <Panel title="Agent Memory Security"><div className="callout"><Database size={15}/> Memory is treated as a security asset with owner, classification, provenance, content integrity and poisoning score.</div><div className="row"><div><b>Memory is not authority</b><small>Stored instructions must remain untrusted data until policy validates them.</small></div><span className="badge">MEMORY</span></div></Panel>
  </div>
  <div className="grid2">
   <Panel title="Transaction Security"><div className="callout"><Receipt size={15}/> Decisions consider transaction value, destination novelty, behavioral ceiling, timing and required approval.</div><div className="row"><div><b>ALLOW · STEP-UP · BLOCK</b><small>Risk-based transaction control rather than tool permission alone.</small></div><span className="badge">TX RISK</span></div></Panel>
   <Panel title="Agent Behavioral DNA"><div className="callout"><Activity size={15}/> Baselines cover tools, destinations, delegation depth, transaction ceilings and action sequences.</div><div className="row"><div><b>Detect behavior drift</b><small>New tools, destinations, delegation or transaction spikes reduce trust.</small></div><span className="badge">BEHAVIOR</span></div></Panel>
  </div>
  <Panel title="AI Security Digital Twin"><div className="callout"><Network size={15}/> Model the blast radius of a compromised agent across identity, delegation, MCP, tools, endpoints, networks and data.</div><div className="row"><div><b>Attack Graph + Trust Graph + Agent Graph</b><small>Generate containment options without executing offensive or destructive actions.</small></div><span className="badge">DIGITAL TWIN</span></div></Panel>
  <Panel title="Production enforcement boundary"><div className="grid2"><div className="callout"><CheckCircle2 size={15}/> VEYRA control plane issues signed/observable decisions and contracts.</div><div className="callout"><PauseCircle size={15}/> Managed workers, identity proxies, network policy and MCP/A2A enforcement points execute the approved controls. VEYRA does not expose arbitrary shell or offensive automation.</div></div></Panel>
 </div>
}
