import React,{useEffect,useState} from 'react';
import {Brain,Search,ShieldAlert,BarChart3,FileSearch,GitBranch,CheckCircle2} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function Panel({title,children}){return <section className="panel"><div className="panelhead"><b>{title}</b><Brain size={16}/></div>{children}</section>}
const auth=()=>({Authorization:`Bearer ${sessionStorage.getItem('VEYRA_user_token')}`,'Content-Type':'application/json'});
export function V50AIApplicationsView(){
 const [apps,setApps]=useState([]),[tab,setTab]=useState('cybsoc_rag'),[q,setQ]=useState('Investigate failed logins followed by suspicious PowerShell execution'),[out,setOut]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{fetch(`${API}/api/v50/ai-applications/catalog`,{headers:auth()}).then(r=>r.ok?r.json():{applications:[]}).then(j=>setApps(j.applications||[])).catch(()=>{})},[]);
 const run=async()=>{setBusy(true);setMsg('');setOut(null);let url='',body={};if(tab==='cybsoc_rag'){url='cybsoc-rag';body={query:q}}else if(tab==='vulnerability_intelligence_rag'){url='vulnerability-rag';body={query:q||'Which vulnerabilities should we patch first and why?'}}else if(tab==='autonomous_research_agent'){url='research-agent';body={query:q}}else if(tab==='agentic_incident_response'){url='incident-response';body={events:[]}}else if(tab==='enterprise_ai_decision_platform'){url='enterprise-decision';body={question:q}}else{url='evaluation';body={}}try{const r=await fetch(`${API}/api/v50/ai-applications/${url}`,{method:'POST',headers:auth(),body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Application run failed');setOut(j)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const render=()=>{if(!out)return <div className="empty">Run the selected application to generate an evidence-linked demo result.</div>;if(tab==='llm_evaluation_reliability')return <div className="table">{Object.entries(out.metrics||{}).map(([k,v])=><div className="row" key={k}><div><b>{k}</b><small>{typeof v==='object'?JSON.stringify(v):v}</small></div></div>)}<div className="callout">Release gate: <b>{out.release_gate?.decision}</b>. Demo values are deterministic fixtures; production runs should be measured from real datasets.</div></div>;if(tab==='vulnerability_intelligence_rag')return <><div className="callout">Risk-aware remediation queue ordered by exposure, KEV, CVSS, criticality and data sensitivity.</div><div className="table">{out.priority_queue?.map(x=><div className="row" key={x.cve}><div><b>{x.asset} · {x.cve}</b><small>Risk {x.risk_score} · {x.reason}</small></div><span className="badge">PATCH PRIORITY</span></div>)}</div></>;return <><div className="callout"><b>{out.answer||out.report||out.attack_stage||''}</b></div><div className="table">{(out.retrieval||out.evidence||[]).map(x=><div className="row" key={x.id||JSON.stringify(x)}><div><b>{x.title||x.id||'Evidence'}</b><small>{x.citation||x.text||JSON.stringify(x)}</small></div><span className="badge">EVIDENCE</span></div>)}</div>{out.timeline&&<Panel title="Incident timeline"><div className="table">{out.timeline.map((e,i)=><div className="row" key={i}><div><b>{e.ts} · {e.event}</b><small>{JSON.stringify(e)}</small></div></div>)}</div></Panel>}{out.stages&&<div className="callout">Workflow: {out.stages.join(' → ')}</div>}</>};
 return <div className="content"><div className="sectionintro"><div><div className="eyebrow">VEYRA v5.0 · AI APPLICATIONS</div><h2>Six portfolio-grade AI security applications</h2><p>One shared RAG, agent, evaluation, evidence and trust platform — six demonstrable POCs.</p></div><span className="badge">FINAL LAYER</span></div><Panel title="Applications"><div style={{display:'flex',gap:7,padding:12,flexWrap:'wrap'}}>{apps.map(a=><button key={a.id} className={tab===a.id?'primary':''} onClick={()=>{setTab(a.id);setOut(null)}}>{a.name.split(' — ')[0]}</button>)}</div></Panel><Panel title="Run the selected POC"><div style={{padding:14,display:'flex',gap:8}}><input style={{flex:1}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Question / investigation task / research topic"/><button className="primary" onClick={run} disabled={busy}>{busy?'Running…':'Run POC'}</button></div>{msg&&<div className="callout">{msg}</div>}</Panel><Panel title="Result"><div style={{padding:14}}>{render()}</div></Panel><div className="grid2"><Panel title="Shared architecture"><div className="callout"><Search size={14}/> Hybrid retrieval → reranking seam → evidence → citations → trust/policy.</div><div className="callout"><GitBranch size={14}/> Agents → tools → graph → evidence → governed decisions.</div></Panel><Panel title="Production readiness"><div className="callout"><CheckCircle2 size={14}/> Every POC records a run, evidence hash and application identity.</div><div className="callout"><ShieldAlert size={14}/> High-risk actions remain approval-gated; these demos never execute offensive or destructive actions.</div></Panel></div></div>
}
