import { LayoutDashboard, Network, Server, TriangleAlert, Cloud, Brain, Database, Users, ScrollText, Search, Activity, LockKeyhole, Globe, GitBranch, Radio, KeyRound, TerminalSquare, Bot, UserCog, ShieldCheck, PackageOpen, Shield } from 'lucide-react';
export const NAV = [
  ['Overview', LayoutDashboard],
  ['Domains & Tools', Globe],
  ['Agents', Bot],
  ['Checklist Library', ScrollText],
  ['Live Operations', Radio],
  ['Team Dashboards', Users],
  ['Trends', Activity],
  ['Red Team', Radio],
  ['Blue Team', Shield],
  ['Security Graph', GitBranch],
  ['Security Operations', TriangleAlert],
  ['Network', Network],
  ['Offensive Security', Search],
  ['Forensics', Globe],
  ['Endpoint', Server],
  ['Cloud', Cloud],
  ['AI Security', Brain],
  ['Data Security', Database],
  ['Identity', Users],
  ['Governance', ScrollText],
  ['Security Fabric', GitBranch],
  ['Autonomous SOC', Activity],
  ['Detection Mesh', TriangleAlert],
  ['Intel Fusion', Globe],
  ['Pentest Agents', Bot],
  ['Tool Runner', TerminalSquare],
  ['User & Permissions', UserCog],
  ['My Password', KeyRound],
  ['Tool Academy', Brain],
  ['Tool Marketplace', PackageOpen],
  ['AI Ecosystem', Brain],
  ['Security Workers', Server],
  ['Adversary Intelligence', Globe],
  ['Wireless Defense', Radio],
  ['Attack Timeline', Activity],
  ['Infrastructure Investigation', Network],
  ['Attribution & Evidence', ShieldCheck],
  ['Full Security Fabric', Shield],
  ['Unified Security Graph', GitBranch],
  ['AI Attack Reconstruction', Activity],
  ['AI SOC Investigator', Brain],
  ['Governed Response & Recovery', ShieldCheck],
  ['Sudo Security Arsenal', ShieldCheck],
  ['Adversary Trace', Search],
  ['Team Security Academy', Brain],
  ['Security Readiness', ShieldCheck],
  ['Continuous Validation', ShieldCheck],
  ['Security Lifecycle', Activity],
  ['Security Radar', Search],
  ['Graph Intelligence', GitBranch],
  ['Posture Time Machine', Activity],
  ['AI Research Lab', Bot],
  ['Update Center', PackageOpen],
  ['Documentation Hub', ScrollText],
  ['Agent Swarm Defense', Bot],
  ['Supply Chain Runtime', ShieldCheck],
  ['Trusted Supply Chain', ShieldCheck],
  ['VEYRA AI Applications', Brain],
  ['VEYRA v5 Control Plane', ShieldCheck],
];
export default NAV;
