import { LayoutDashboard, Network, Server, TriangleAlert, Cloud, Brain, Database, Users, ScrollText, Search, Activity, LockKeyhole, Globe, GitBranch, Radio, KeyRound, TerminalSquare, Bot, UserCog, ShieldCheck, PackageOpen, Shield } from 'lucide-react';
export const NAV = [
  ['Overview', LayoutDashboard],
  ['Domains & Tools', Globe],
  ['Agents', Bot],
  ['Checklist Library', ScrollText],
  ['Live Operations', Radio],
  ['Team Dashboards', Users],
  ['Trends', Activity],
  ['Red Team', Radio],
  ['Blue Team', Shield],
  ['Security Graph', GitBranch],
  ['Security Operations', TriangleAlert],
  ['Network', Network],
  ['Offensive Security', Search],
  ['Forensics', Globe],
  ['Endpoint', Server],
  ['Cloud', Cloud],
  ['AI Security', Brain],
  ['Data Security', Database],
  ['Identity', Users],
  ['Governance', ScrollText],
  ['Security Fabric', GitBranch],
  ['Autonomous SOC', Activity],
  ['Detection Mesh', TriangleAlert],
  ['Intel Fusion', Globe],
  ['Pentest Agents', Bot],
  ['Tool Runner', TerminalSquare],
  ['User & Permissions', UserCog],
  ['My Password', KeyRound],
  ['Tool Academy', Brain],
  ['Tool Marketplace', PackageOpen],
  ['AI Ecosystem', Brain],
  ['Security Workers', Server],
  ['Adversary Intelligence', Globe],
  ['Wireless Defense', Radio],
  ['Attack Timeline', Activity],
  ['Infrastructure Investigation', Network],
  ['Attribution & Evidence', ShieldCheck],
  ['Full Security Fabric', Shield],
  ['Unified Security Graph', GitBranch],
  ['AI Attack Reconstruction', Activity],
  ['AI SOC Investigator', Brain],
  ['Governed Response & Recovery', ShieldCheck],
  ['Sudo Security Arsenal', ShieldCheck],
  ['Adversary Trace', Search],
  ['Team Security Academy', Brain],
  ['Security Readiness', ShieldCheck],
  ['Continuous Validation', ShieldCheck],
  ['Security Lifecycle', Activity],
  ['Security Radar', Search],
  ['Graph Intelligence', GitBranch],
  ['Posture Time Machine', Activity],
  ['AI Research Lab', Bot],
  ['Update Center', PackageOpen],
  ['Documentation Hub', ScrollText],
  ['Agent Swarm Defense', Bot],
  ['Supply Chain Runtime', ShieldCheck],
  ['Trusted Supply Chain', ShieldCheck],
  ['VEYRA AI Applications', Brain],
  ['VEYRA v5 Control Plane', ShieldCheck],
];

// Grouped by the 8 CISSP-style security domains (user request) + Platform/AI/Supply Chain
export const GROUPED_NAV = [
  ['PLATFORM OVERVIEW', [
    ['Overview', LayoutDashboard],
    ['Domains & Tools', Globe],
    ['Agents', Bot],
    ['Checklist Library', ScrollText],
    ['Live Operations', Radio],
    ['Team Dashboards', Users],
    ['Trends', Activity],
  ]],
  ['1. Network Security', [
    ['Network', Network],
    ['Wireless Defense', Radio],
    ['Security Fabric', GitBranch],
    ['Full Security Fabric', Shield],
    ['Security Graph', GitBranch],
    ['Unified Security Graph', GitBranch],
    ['Graph Intelligence', GitBranch],
  ]],
  ['2. Identity & Access Management', [
    ['Identity', Users],
    ['User & Permissions', UserCog],
    ['Sudo Security Arsenal', ShieldCheck],
    ['My Password', KeyRound],
  ]],
  ['3. Application Security', [
    ['Offensive Security', Search],
    ['Pentest Agents', Bot],
    ['Tool Runner', TerminalSquare],
    ['Adversary Trace', Search],
    ['Continuous Validation', ShieldCheck],
    ['Security Radar', Search],
    ['Posture Time Machine', Activity],
  ]],
  ['4. Cloud Security', [
    ['Cloud', Cloud],
    ['Update Center', PackageOpen],
  ]],
  ['5. Endpoint Security', [
    ['Endpoint', Server],
  ]],
  ['6. SecOps & Incident Response', [
    ['Security Operations', TriangleAlert],
    ['Autonomous SOC', Activity],
    ['Detection Mesh', TriangleAlert],
    ['Intel Fusion', Globe],
    ['Forensics', Globe],
    ['Adversary Intelligence', Globe],
    ['Attack Timeline', Activity],
    ['Infrastructure Investigation', Network],
    ['Attribution & Evidence', ShieldCheck],
    ['Governed Response & Recovery', ShieldCheck],
    ['Red Team', Radio],
    ['Blue Team', Shield],
  ]],
  ['7. Data Security & Cryptography', [
    ['Data Security', Database],
  ]],
  ['8. Governance, Risk & Compliance', [
    ['Governance', ScrollText],
    ['Security Readiness', ShieldCheck],
    ['Security Lifecycle', Activity],
    ['Team Security Academy', Brain],
    ['Documentation Hub', ScrollText],
  ]],
  ['9. AI & Automation', [
    ['AI Security', Brain],
    ['AI Ecosystem', Brain],
    ['VEYRA AI Applications', Brain],
    ['AI Research Lab', Bot],
    ['AI Attack Reconstruction', Activity],
    ['AI SOC Investigator', Brain],
    ['Agent Swarm Defense', Bot],
    ['VEYRA v5 Control Plane', ShieldCheck],
  ]],
  ['10. Supply Chain & Workers', [
    ['Supply Chain Runtime', ShieldCheck],
    ['Trusted Supply Chain', ShieldCheck],
    ['Tool Academy', Brain],
    ['Tool Marketplace', PackageOpen],
    ['Security Workers', Server],
  ]],
];
export default NAV;
